vector < string > SeparateParenGroups ( string paren_string ) { vector < string > all_parens ; string current_paren ; int current_depth = 0 ; for ( auto c : paren_string ) { if ( c == '(' ) { current_depth += 1 ; current_paren += c ; } else if ( c == ')' ) { current_depth -= 1 ; current_paren += c ; if ( current_depth == 0 ) { all_parens . push_back ( current_paren ) ; current_paren . clear ( ) ; } } } return all_parens ; } 
vector < int > ParseNestedParens ( string paren_string ) { vector < int > all_levels ; int level = 0 ; int max_level = 0 ; for ( int i = 0 ; i < paren_string . length ( ) ; i ++ ) { char chr = paren_string [ i ] ; if ( chr == '(' ) { level += 1 ; if ( level > max_level ) { max_level = level ; } } if ( chr == ')' ) { level -= 1 ; if ( level == 0 ) { all_levels . push_back ( max_level ) ; max_level = 0 ; } } } return all_levels ; } 
vector < string > FilterBySubstring ( vector < string > strings , string substring ) { vector < string > result ; for ( auto & s : strings ) { if ( s . find ( substring ) != string :: npos ) { result . push_back ( s ) ; } } return result ; } 
vector < int > RollingMax ( vector < int > numbers ) { int running_max = 0 ; vector < int > result ; for ( int n : numbers ) { if ( n > running_max ) { running_max = n ; } result . push_back ( running_max ) ; } return result ; } 
string MakePalindrome ( string s ) { if ( s . empty ( ) ) { return "" ; } for ( int i = 0 ; i < s . length ( ) ; i ++ ) { string r_str = s . substr ( i ) ; if ( r_str == string ( r_str . rbegin ( ) , r_str . rend ( ) ) ) { string n_str = s . substr ( 0 , i ) ; string n2_str ( n_str . rbegin ( ) , n_str . rend ( ) ) ; return s + n2_str ; } } return s . substr ( 0 , s . length ( ) - 1 ) + string ( s . rbegin ( ) , s . rend ( ) ) ; } 
string StringXor ( string a , string b ) { string result ; for ( int i = 0 ; i < a . length ( ) ; i ++ ) { if ( a [ i ] == b [ i ] ) { result += '0' ; } else { result += '1' ; } } return result ; } 
string Longest ( vector < string > strings ) { if ( strings . empty ( ) ) { return "" ; } int max_len = ranges :: max ( views :: transform ( strings , & string :: size ) ) ; for ( auto & s : strings ) { if ( s . length ( ) == max_len ) { return s ; } } return "" ; } 
string StringSequence ( int n ) { string s ; for ( int i = 0 ; i < n ; i ++ ) { s += to_string ( i ) ; s += " " ; } s += to_string ( n ) ; return s ; } 
int CountDistinctCharacter ( string s ) { unordered_set < char > distinct ; for ( char c : views :: transform ( s , :: tolower ) ) { distinct . insert ( c ) ; } return distinct . size ( ) ; } 
int HowManyTimes ( string s , string sub ) { int times = 0 ; for ( int i = 0 ; i <= int ( s . length ( ) - sub . length ( ) ) ; i ++ ) { if ( s . substr ( i , sub . length ( ) ) == sub ) { times += 1 ; } } return times ; } 
string SortNumbers ( string numbers ) { unordered_map < string , int > to_num = { { "zero" , 0 } , { "one" , 1 } , { "two" , 2 } , { "three" , 3 } , { "four" , 4 } , { "five" , 5 } , { "six" , 6 } , { "seven" , 7 } , { "eight" , 8 } , { "nine" , 9 } } ; unordered_map < int , string > from_num = { { 0 , "zero" } , { 1 , "one" } , { 2 , "two" } , { 3 , "three" } , { 4 , "four" } , { 5 , "five" } , { 6 , "six" } , { 7 , "seven" } , { 8 , "eight" } , { 9 , "nine" } } ; vector < int > ints ; string current ; for ( int i = 0 ; i <= numbers . length ( ) ; i ++ ) { if ( i == numbers . length ( ) || numbers [ i ] == ' ' ) { if ( to_num . count ( current ) ) { ints . push_back ( to_num [ current ] ) ; current . clear ( ) ; } } else { current += numbers [ i ] ; } } sort ( ints . begin ( ) , ints . end ( ) ) ; string result ; for ( int i = 0 ; i < ints . size ( ) ; i ++ ) { result += from_num [ ints [ i ] ] ; if ( i != ints . size ( ) - 1 ) { result += " " ; } } return result ; } 
vector < double > FindClosestElements ( vector < double > numbers ) { vector < double > closest_pair { numbers [ 0 ] , numbers [ 1 ] } ; double distance = abs ( closest_pair [ 0 ] - closest_pair [ 1 ] ) ; for ( int i = 0 ; i < numbers . size ( ) ; i ++ ) { for ( int j = i + 1 ; j < numbers . size ( ) ; j ++ ) { if ( abs ( numbers [ i ] - numbers [ j ] ) < distance ) { closest_pair [ 0 ] = numbers [ i ] ; closest_pair [ 1 ] = numbers [ j ] ; distance = abs ( numbers [ i ] - numbers [ j ] ) ; } } } sort ( closest_pair . begin ( ) , closest_pair . end ( ) ) ; return closest_pair ; } 
vector < double > RescaleToUnit ( vector < double > numbers ) { double min_num = * min_element ( numbers . begin ( ) , numbers . end ( ) ) ; double max_num = * max_element ( numbers . begin ( ) , numbers . end ( ) ) ; vector < double > result ; for ( double n : numbers ) { result . push_back ( ( n - min_num ) / ( max_num - min_num ) ) ; } return result ; } 
vector < int > FilterIntegers ( vector < any > values ) { vector < int > result ; for ( auto & e : values ) { if ( e . type ( ) == typeid ( int ) ) { result . push_back ( any_cast < int > ( e ) ) ; } } return result ; } 
vector < int > removeDuplicates ( vector < int > numbers ) { unordered_map < int , int > counter ; for ( int i : numbers ) { counter [ i ] = counter [ i ] + 1 ; } vector < int > result ; for ( int i : numbers ) { if ( counter [ i ] == 1 ) { result . push_back ( i ) ; } } return result ; } 
string FlipCase ( string s ) { string result ; for ( char c : s ) { if ( islower ( c ) ) { result += toupper ( c ) ; } else { result += tolower ( c ) ; } } return result ; } 
vector < string > FilterByPrefix ( vector < string > strings , string prefix ) { vector < string > result ; for ( int i = 0 ; i < strings . size ( ) ; i ++ ) { if ( strings [ i ] . starts_with ( prefix ) ) { result . push_back ( strings [ i ] ) ; } } return result ; } 
double FindZero ( vector < double > xs ) { double ans = 0 ; double value = 0 ; for ( int i = 0 ; i < xs . size ( ) ; i ++ ) { value += xs [ i ] * pow ( ans , i ) ; } while ( abs ( value ) > 1e-6 ) { double driv = 0 ; for ( int i = 1 ; i < xs . size ( ) ; i ++ ) { driv += xs [ i ] * pow ( ans , i - 1 ) * i ; } ans -= value / driv ; value = 0 ; for ( int i = 0 ; i < xs . size ( ) ; i ++ ) { value += xs [ i ] * pow ( ans , i ) ; } } return ans ; } 
vector < int > SortThird ( vector < int > l ) { vector < int > thirds ; for ( int i = 0 ; i < l . size ( ) ; i += 3 ) { thirds . push_back ( l [ i ] ) ; } sort ( thirds . begin ( ) , thirds . end ( ) ) ; vector < int > result ; for ( int i = 0 ; i < l . size ( ) ; i ++ ) { if ( i % 3 == 0 ) { result . push_back ( thirds [ i / 3 ] ) ; } else { result . push_back ( l [ i ] ) ; } } return result ; } 
vector < int > Unique ( vector < int > l ) { unordered_set < int > s ( l . begin ( ) , l . end ( ) ) ; vector < int > result ( s . begin ( ) , s . end ( ) ) ; sort ( result . begin ( ) , result . end ( ) ) ; return result ; } 
double MaxElement ( vector < double > l ) { return * max_element ( l . begin ( ) , l . end ( ) ) ; } 
bool TriplesSumToZero ( vector < int > l ) { for ( int i = 0 ; i < l . size ( ) ; i ++ ) { for ( int j = i + 1 ; j < l . size ( ) ; j ++ ) { for ( int k = j + 1 ; k < l . size ( ) ; k ++ ) { if ( l [ i ] + l [ j ] + l [ k ] == 0 ) { return true ; } } } } return false ; } 
int Fib4 ( int n ) { vector < int > results { 0 , 0 , 2 , 0 } ; for ( int i = 4 ; i <= n ; i ++ ) { results . push_back ( results [ i - 4 ] + results [ i - 3 ] + results [ i - 2 ] + results [ i - 1 ] ) ; } return results [ n ] ; } 
bool IsPalindrome ( string text ) { string pr ( text . rbegin ( ) , text . rend ( ) ) ; return pr == text ; } 
string RemoveVowels ( string text ) { string result ; string vowels = "aeiou" ; for ( char ch : text ) { if ( vowels . find ( tolower ( ch ) ) == string :: npos ) { result += ch ; } } return result ; } 
bool SameChars ( string s0 , string s1 ) { unordered_set < char > set0 ; for ( char c : s0 ) { set0 . insert ( c ) ; } unordered_set < char > set1 ; for ( char c : s1 ) { set1 . insert ( c ) ; } return set0 == set1 ; } 
vector < int > Common ( vector < int > l1 , vector < int > l2 ) { unordered_set < int > us ; for ( int e1 : l1 ) { for ( int e2 : l2 ) { if ( e1 == e2 ) { us . insert ( e1 ) ; } } } vector < int > ret ( us . begin ( ) , us . end ( ) ) ; sort ( ret . begin ( ) , ret . end ( ) ) ; return ret ; } 
bool CorrectBracketing ( string brackets ) { int depth = 0 ; for ( char b : brackets ) { if ( b == '(' ) { depth += 1 ; } if ( b == ')' ) { depth -= 1 ; } if ( depth < 0 ) { return false ; } } return depth == 0 ; } 
string CircularShift ( int x , int shift ) { string xs = to_string ( x ) ; if ( shift > xs . length ( ) ) { return string ( xs . rbegin ( ) , xs . rend ( ) ) ; } return xs . substr ( xs . length ( ) - shift ) + xs . substr ( 0 , xs . length ( ) - shift ) ; } 
int Search ( vector < int > lst ) { unordered_map < int , int > counter ; for ( int i : lst ) { counter [ i ] += 1 ; } int ans = -1 ; for ( auto & [ key , value ] : counter ) { if ( value >= key && key > ans ) { ans = key ; } } return ans ; } 
int SmallestChange ( vector < int > arr ) { int ans = 0 ; for ( int i = 0 ; i < arr . size ( ) / 2 ; i ++ ) { if ( arr [ i ] != arr [ arr . size ( ) - i - 1 ] ) { ans += 1 ; } } return ans ; } 
vector < string > TotalMatch ( vector < string > lst1 , vector < string > lst2 ) { int sum1 = 0 ; for ( auto & st : lst1 ) { sum1 += st . length ( ) ; } int sum2 = 0 ; for ( auto & st : lst2 ) { sum2 += st . length ( ) ; } return sum1 > sum2 ? lst2 : lst1 ; } 
bool IsHappy ( string s ) { if ( s . length ( ) < 3 ) { return false ; } for ( int i = 0 ; i < s . length ( ) - 2 ; i ++ ) { if ( s [ i ] == s [ i + 1 ] || s [ i ] == s [ i + 2 ] || s [ i + 1 ] == s [ i + 2 ] ) { return false ; } } return true ; } 
vector < string > NumericalLetterGrade ( vector < double > grades ) { vector < string > letter_grade ; for ( double gpa : grades ) { if ( gpa == 4.0 ) { letter_grade . push_back ( "A+" ) ; } else if ( gpa > 3.7 ) { letter_grade . push_back ( "A" ) ; } else if ( gpa > 3.3 ) { letter_grade . push_back ( "A-" ) ; } else if ( gpa > 3.0 ) { letter_grade . push_back ( "B+" ) ; } else if ( gpa > 2.7 ) { letter_grade . push_back ( "B" ) ; } else if ( gpa > 2.3 ) { letter_grade . push_back ( "B-" ) ; } else if ( gpa > 2.0 ) { letter_grade . push_back ( "C+" ) ; } else if ( gpa > 1.7 ) { letter_grade . push_back ( "C" ) ; } else if ( gpa > 1.3 ) { letter_grade . push_back ( "C-" ) ; } else if ( gpa > 1.0 ) { letter_grade . push_back ( "D+" ) ; } else if ( gpa > 0.7 ) { letter_grade . push_back ( "D" ) ; } else if ( gpa > 0.0 ) { letter_grade . push_back ( "D-" ) ; } else { letter_grade . push_back ( "E" ) ; } } return letter_grade ; } 
string Solve ( int n ) { string bi_str ; int sum = 0 ; for ( char c : to_string ( n ) ) { sum += c - '0' ; } while ( sum > 0 ) { bi_str . insert ( 0 , to_string ( sum % 2 ) ) ; sum /= 2 ; } return bi_str ; } 
string AntiShuffle ( string s ) { string ret ; string current ; for ( int i = 0 ; i <= s . length ( ) ; i ++ ) { if ( i == s . length ( ) || s [ i ] == ' ' ) { sort ( current . begin ( ) , current . end ( ) ) ; if ( ! ret . empty ( ) ) { ret += ' ' ; } ret += current ; current . clear ( ) ; } else { current += s [ i ] ; } } return ret ; } 
vector < int > SortArray ( vector < int > array ) { if ( array . empty ( ) ) { return array ; } if ( ( array [ 0 ] + array [ array . size ( ) - 1 ] ) % 2 == 1 ) { sort ( array . begin ( ) , array . end ( ) ) ; } else { sort ( array . begin ( ) , array . end ( ) , greater < > ( ) ) ; } return array ; } 
string Encrypt ( string s ) { string ans ; for ( char c : s ) { if ( isalpha ( c ) ) { ans += ( char ) ( 'a' + ( c - 'a' + 4 ) % 26 ) ; } else { ans += c ; } } return ans ; } 
int IsBored ( string s ) { bool is_start = true ; int sum = 0 ; for ( int i = 0 ; i < s . length ( ) ; i ++ ) { if ( s [ i ] == '.' || s [ i ] == '?' || s [ i ] == '!' ) { is_start = true ; } else if ( is_start ) { if ( s [ i ] == ' ' ) { continue ; } if ( s . substr ( i , 2 ) == "I " ) { sum += 1 ; } is_start = false ; } } return sum ; } 
string Encode ( string message ) { string vowels = "aeiouAEIOU" ; string ret ; for ( char c : message ) { if ( isupper ( c ) ) { c = tolower ( c ) ; if ( vowels . find ( c ) != string :: npos ) { c = 'a' + ( c - 'a' + 2 ) % 26 ; } } else if ( islower ( c ) ) { c = toupper ( c ) ; if ( vowels . find ( c ) != string :: npos ) { c = 'A' + ( c - 'A' + 2 ) % 26 ; } } ret += c ; } return ret ; } 
int Skjkasdkd ( vector < int > lst ) { int largest = 0 ; for ( int n : lst ) { if ( n > largest ) { bool prime = true ; for ( int i = 2 ; i < n ; i ++ ) { if ( n % i == 0 ) { prime = false ; } } if ( prime ) { largest = n ; } } } int sum = 0 ; string s = to_string ( largest ) ; for ( int i = 0 ; i < s . length ( ) ; i ++ ) { sum += s [ i ] - '0' ; } return sum ; } 
bool CheckDictCase ( unordered_map < string , string > dict ) { if ( dict . empty ( ) ) { return false ; } int is_lower = 0 ; int is_upper = 0 ; for ( auto & [ key , value ] : dict ) { for ( char c : key ) { if ( islower ( c ) ) { is_lower = 1 ; } else if ( isupper ( c ) ) { is_upper = 1 ; } else { return false ; } } } return is_lower + is_upper == 1 ; } 
int Multiply ( int a , int b ) { return ( abs ( a ) % 10 ) * ( abs ( b ) % 10 ) ; } 
int CountUpper ( string s ) { string u_vowel = "AEIOU" ; int count = 0 ; for ( int i = 0 ; i < s . length ( ) ; i += 2 ) { if ( u_vowel . find ( s [ i ] ) != string :: npos ) { count += 1 ; } } return count ; } 
vector < string > ByLength ( vector < int > arr ) { map < int , string > num_to = { { 1 , "One" } , { 2 , "Two" } , { 3 , "Three" } , { 4 , "Four" } , { 5 , "Five" } , { 6 , "Six" } , { 7 , "Seven" } , { 8 , "Eight" } , { 9 , "Nine" } } ; vector < int > sorted_arr ( arr ) ; sort ( sorted_arr . begin ( ) , sorted_arr . end ( ) , greater < > ( ) ) ; vector < string > new_arr ; for ( int n : sorted_arr ) { if ( n >= 1 && n <= 9 ) { new_arr . push_back ( num_to [ n ] ) ; } } return new_arr ; } 
vector < int > f ( int n ) { int sum = 0 ; int prod = 1 ; vector < int > result ; for ( int i = 1 ; i <= n ; i ++ ) { sum += i ; prod *= i ; if ( i % 2 == 0 ) { result . push_back ( prod ) ; } else { result . push_back ( sum ) ; } } return result ; } 
vector < int > EvenOddPalindrome ( int n ) { int even_count = 0 , odd_count = 0 ; for ( int i = 1 ; i <= n ; i ++ ) { string s = to_string ( i ) ; string r_str ( s . rbegin ( ) , s . rend ( ) ) ; if ( s == r_str ) { if ( i % 2 == 1 ) { odd_count += 1 ; } else { even_count += 1 ; } } } return { even_count , odd_count } ; } 
unordered_map < char , int > Histogram ( string test ) { unordered_map < char , int > count ; int max = 0 ; for ( int i = 0 ; i < test . length ( ) ; i ++ ) { if ( test [ i ] != ' ' ) { count [ test [ i ] ] += 1 ; if ( count [ test [ i ] ] > max ) { max = count [ test [ i ] ] ; } } } unordered_map < char , int > result ; for ( auto & [ key , value ] : count ) { if ( value == max ) { result [ key ] = value ; } } return result ; } 
vector < string > ReverseDelete ( string s , string c ) { string ret ; for ( char ch : s ) { if ( c . find ( ch ) == string :: npos ) { ret += ch ; } } string flag = "False" ; if ( ret == string ( ret . rbegin ( ) , ret . rend ( ) ) ) { flag = "True" ; } return { ret , flag } ; } 
vector < int > SortArray ( vector < int > arr ) { vector < int > bin ; for ( int i : arr ) { int b = 0 ; int n = abs ( i ) ; while ( n > 0 ) { b += n % 2 ; n /= 2 ; } bin . push_back ( b ) ; } for ( int i = 0 ; i < arr . size ( ) ; i ++ ) { for ( int j = 1 ; j < arr . size ( ) ; j ++ ) { if ( bin [ j ] < bin [ j - 1 ] || ( bin [ j ] == bin [ j - 1 ] && arr [ j ] < arr [ j - 1 ] ) ) { swap ( bin [ j ] , bin [ j - 1 ] ) ; swap ( arr [ j ] , arr [ j - 1 ] ) ; } } } return arr ; } 
string GetClosestVowel ( string word ) { string vowels = "AEIOUaeiou" ; for ( int i = word . length ( ) - 2 ; i > 0 ; i -- ) { if ( vowels . find ( word [ i ] ) != string :: npos && vowels . find ( word [ i + 1 ] ) == string :: npos && vowels . find ( word [ i - 1 ] ) == string :: npos ) { return string ( 1 , word [ i ] ) ; } } return "" ; } 
string MatchParens ( vector < string > lst ) { vector < string > strings = { lst [ 0 ] + lst [ 1 ] , lst [ 1 ] + lst [ 0 ] } ; for ( auto & l : strings ) { int count = 0 ; for ( char c : l ) { if ( c == '(' ) { count += 1 ; } if ( c == ')' ) { count -= 1 ; } if ( count < 0 ) { break ; } } if ( count == 0 ) { return "Yes" ; } } return "No" ; } 
vector < int > Maximum ( vector < int > arr , int k ) { if ( k == 0 ) { return { } ; } sort ( arr . begin ( ) , arr . end ( ) ) ; return vector < int > ( arr . end ( ) - k , arr . end ( ) ) ; } 
bool ValidDate ( string date ) { if ( date . length ( ) != 10 ) { return false ; } for ( int i = 0 ; i < 10 ; i ++ ) { if ( i == 2 || i == 5 ) { if ( date [ i ] != '-' ) { return false ; } } else if ( ! isdigit ( date [ i ] ) ) { return false ; } } int month = stoi ( date . substr ( 0 , 2 ) ) ; int day = stoi ( date . substr ( 3 , 2 ) ) ; int year = stoi ( date . substr ( 6 , 4 ) ) ; if ( month < 1 || month > 12 ) { return false ; } if ( day < 1 || day > 31 ) { return false ; } if ( day == 31 && ( month == 4 || month == 6 || month == 9 || month == 11 || month == 2 ) ) { return false ; } if ( day == 30 && month == 2 ) { return false ; } return true ; } 
vector < string > SplitWords ( string txt ) { string current ; vector < string > result ; if ( txt . find ( ' ' ) != string :: npos ) { for ( int i = 0 ; i <= txt . length ( ) ; i ++ ) { if ( i == txt . length ( ) || txt [ i ] == ' ' ) { if ( current . length ( ) > 0 ) { result . push_back ( current ) ; } current . clear ( ) ; } else { current += txt [ i ] ; } } return result ; } if ( txt . find ( ',' ) != string :: npos ) { for ( int i = 0 ; i <= txt . length ( ) ; i ++ ) { if ( i == txt . length ( ) || txt [ i ] == ',' ) { if ( current . length ( ) > 0 ) { result . push_back ( current ) ; } current . clear ( ) ; } else { current += txt [ i ] ; } } return result ; } int num = 0 ; for ( char c : txt ) { if ( islower ( c ) && c % 2 == 0 ) { num += 1 ; } } return { to_string ( num ) } ; } 
vector < int > Tri ( int n ) { if ( n == 0 ) { return { 1 } ; } vector < int > tris = { 1 , 3 } ; for ( int i = 2 ; i <= n ; i ++ ) { if ( i % 2 == 0 ) { tris . push_back ( i / 2 + 1 ) ; } else { tris . push_back ( tris [ i - 1 ] + tris [ i - 2 ] + ( i + 3 ) / 2 ) ; } } return tris ; } 
bool CheckIfLastCharIsALetter ( string txt ) { if ( txt . empty ( ) ) { return false ; } return isalpha ( txt [ txt . length ( ) - 1 ] ) && ( txt . length ( ) == 1 || ! isalpha ( txt [ txt . length ( ) - 2 ] ) ) ; } 
vector < int > OrderByPoints ( vector < int > nums ) { vector < int > result ; for ( int num : nums ) { string w = to_string ( abs ( num ) ) ; int sum = 0 ; for ( char c : w ) { sum += c - '0' ; } if ( num < 0 ) { sum -= 2 * ( w [ 0 ] - '0' ) ; } result . push_back ( sum ) ; } for ( int i = 0 ; i < nums . size ( ) ; i ++ ) { for ( int j = 1 ; j < nums . size ( ) ; j ++ ) { if ( result [ j - 1 ] > result [ j ] ) { swap ( result [ j ] , result [ j - 1 ] ) ; swap ( nums [ j ] , nums [ j - 1 ] ) ; } } } return nums ; } 
vector < string > Bf ( string planet1 , string planet2 ) { vector < string > planets = { "Mercury" , "Venus" , "Earth" , "Mars" , "Jupiter" , "Saturn" , "Uranus" , "Neptune" } ; auto it1 = find ( planets . begin ( ) , planets. end ( ) , planet1 ) ; int idx1 = it1 == planets . end ( ) ? -1 : it1 - planets . begin ( ) ; auto it2 = find ( planets . begin ( ) , planets . end ( ) , planet2 ) ; int idx2 = it2 == planets . end ( ) ? -1 : it2 - planets . begin ( ) ; if ( idx1 == -1 || idx2 == -1 || idx1 == idx2 ) { return { } ; } return idx1 > idx2 ? vector < string > ( planets . begin ( ) + idx2 + 1 , planets . begin ( ) + idx1 ) : vector < string > ( planets . begin ( ) + idx1 + 1 , planets . begin ( ) + idx2 ) ; } 
vector < string > SortedListSum ( vector < string > lst ) { vector < string > result ; for ( auto & i : lst ) { if ( i . length ( ) % 2 == 0 ) { result . push_back ( i ) ; } } sort ( result . begin ( ) , result . end ( ) , [ ] ( string & l , string & r ) { if ( l . length ( ) == r . length ( ) ) { return l < r ; } return l . length ( ) < r . length ( ) ; } ) ; return result ; } 
bool CycpatternCheck ( string a , string b ) { for ( int i = 0 ; i < b . length ( ) ; i ++ ) { string rotate = b . substr ( i ) + b . substr ( 0 , i ) ; if ( a . find ( rotate ) != string :: npos ) { return true ; } } return false ; } 
vector < int > EvenOddCount ( int num ) { int even_count = 0 , odd_count = 0 ; for ( char i : to_string ( abs ( num ) ) ) { if ( i % 2 == 0 ) { even_count += 1 ; } else { odd_count += 1 ; } } return { even_count , odd_count } ; } 
string FindMax ( vector < string > words ) { string max ; int max_length = 0 ; for ( auto & word : words ) { vector < char > unique ; for ( char w : word ) { if ( find ( unique . begin ( ) , unique . end ( ) , w ) == unique . end ( ) ) { unique . push_back ( w ) ; } } if ( unique . size ( ) > max_length || ( unique . size ( ) == max_length && word < max ) ) { max = word ; max_length = unique . size ( ) ; } } return max ; } 
string Solve ( string s ) { bool no_letter = true ; string result ; for ( char ch : s ) { if ( isupper ( ch ) ) { ch = tolower ( ch ) ; no_letter = false ; } else if ( islower ( ch ) ) { ch = toupper ( ch ) ; no_letter = false ; } result += ch ; } if ( no_letter ) { return string ( s . rbegin ( ) , s . rend ( ) ) ; } else { return result ; } } 
int MostFrequent ( vector < int > arr , int n ) { unordered_map < int , int > hp ; for ( int i = 0 ; i < n ; i ++ ) { if ( hp . find ( arr [ i ] ) != hp . end ( ) ) { hp [ arr [ i ] ] ++ ; } else { hp [ arr [ i ] ] = 1 ; } } int max_count = 0 , res = -1 ; for ( auto & entry : hp ) { if ( max_count < entry . second ) { res = entry . first ; max_count = entry . second ; } } return res ; } 
int Find ( vector < int > a , vector < int > b , int k , int n1 , int n2 ) { unordered_set < int > s ; for ( int i = 0 ; i < n2 ; i ++ ) { s . insert ( b [ i ] ) ; } int missing = 0 ; for ( int i = 0 ; i < n1 ; i ++ ) { if ( s . find ( a [ i ] ) == s . end ( ) ) { missing ++ ; } if ( missing == k ) { return a [ i ] ; } } return -1 ; } 
int SolveQuery ( int start , int end , vector < int > arr ) { unordered_map < int , int > mp ; for ( int i = start ; i <= end ; i ++ ) { mp [ arr [ i ] ] ++ ; } int count = 0 ; for ( auto & [ key , value ] : mp ) { if ( key == value ) { count ++ ; } } return count ; } 
int Segregate ( vector < int > arr , int size ) { int j = 0 ; for ( int i = 0 ; i < size ; i ++ ) { if ( arr [ i ] <= 0 ) { swap ( arr [ i ] , arr [ j ] ) ; j ++ ; } } return j ; } 
int CountTriplets ( vector < int > a , int n ) { unordered_set < int > s ; for ( int i = 0 ; i < n ; i ++ ) { s . insert ( a [ i ] ) ; } int count = 0 ; for ( int i = 0 ; i < n - 1 ; i ++ ) { for ( int j = i + 1 ; j < n ; j ++ ) { int xr = a [ i ] ^ a [ j ] ; if ( s . find ( xr ) != s . end ( ) && xr != a [ i ] && xr != a [ j ] ) { count ++ ; } } } return count / 3 ; } 
int LeastFrequent ( vector < int > arr , int n ) { unordered_map < int , int > hp ; for ( int i = 0 ; i < n ; i ++ ) { if ( hp . find ( arr [ i ] ) != hp . end ( ) ) { hp [ arr [ i ] ] ++ ; } else { hp [ arr [ i ] ] = 1 ; } } int min_count = n + 1 , res = -1 ; for ( auto & entry : hp ) { if ( min_count >= entry . second ) { res = entry . first ; min_count = entry . second ; } } return res ; } 
int FindPermutations ( vector < int > arr ) { int cnt = 0 ; int max_ind = -1 , min_ind = 10000000 ; int n = arr . size ( ) ; unordered_map < int , int > index_of ; for ( int i = 0 ; i < n ; i ++ ) { index_of [ arr [ i ] ] = i + 1 ; } for ( int i = 1 ; i <= n ; i ++ ) { max_ind = max ( max_ind , index_of [ i ] ) ; min_ind = min ( min_ind , index_of [ i ] ) ; if ( max_ind - min_ind + 1 == i ) { cnt ++ ; } } return cnt ; } 
int FormQuadruplets ( vector < int > arr , int n ) { int ans = 0 , pairs = 0 ; pairs = n / 4 ; sort ( arr . begin ( ) , arr . end ( ) , greater < > ( ) ) ; for ( int i = 0 ; i < n - pairs ; i += 3 ) { ans += arr [ i + 2 ] ; } return ans ; } 
string LexicographicallyMaximum ( string s , int n ) { unordered_map < char , int > m ; for ( int i = 0 ; i < n ; ++ i ) { if ( m . find ( s [ i ] ) != m . end ( ) ) { m [ s [ i ] ] ++ ; } else { m [ s [ i ] ] = 1 ; } } vector < char > v ; for ( char i = 'a' ; i < 'a' + min ( n , 25 ) ; ++ i ) { if ( m . find ( i ) == m . end ( ) ) { v . push_back ( i ) ; } } int j = v . size ( ) - 1 ; for ( int i = 0 ; i < n ; ++ i ) { if ( s [ i ] >= 'a' + min ( n , 25 ) || ( m . find ( s [ i ] ) != m . end ( ) && m [ s [ i ] ] > 1 ) ) { if ( v [ j ] < s [ i ] ) { continue ; } m [ s [ i ] ] -- ; s = s . substr ( 0 , i ) + v [ j ] + s . substr ( i + 1 ) ; j -- ; } if ( j < 0 ) { break ; } } int l = 0 ; for ( int i = n - 1 ; i >= 0 ; i -- ) { if ( l > j ) { break ; } if ( s [ i ] >= 'a' + min ( n , 25 ) || ( m . find ( s [ i ] ) != m . end ( ) && m [ s [ i ] ] > 1 ) ) { m [ s [ i ] ] -- ; s = s . substr ( 0 , i ) + v [ l ] + s . substr ( i + 1 ) ; l ++ ; } } return s ; } 
int NoOfValidKbers ( int k , vector < int > arr ) { unordered_set < int > s ; while ( k != 0 ) { s . insert ( k % 10 ) ; k = k / 10 ; } int count = 0 ; for ( int i = 0 ; i < arr . size ( ) ; i ++ ) { int no = arr [ i ] ; bool flag = true ; while ( no != 0 ) { int digit = no % 10 ; if ( s . find ( digit ) == s . end ( ) ) { flag = false ; break ; } no = no / 10 ; } if ( flag ) { count ++ ; } } return count ; } 
int DelCost ( string s , vector < int > cost ) { int ans = 0 ; map < char , int > for_max ; map < char , int > for_tot ; for ( int i = 0 ; i < s . length ( ) ; i ++ ) { if ( for_max . find ( s [ i ] ) == for_max . end ( ) ) { for_max [ s [ i ] ] = cost [ i ] ; } else { for_max [ s [ i ] ] = max ( cost [ i ] , for_max [ s [ i ] ] ) ; } if ( for_tot . find ( s [ i ] ) == for_tot . end ( ) ) { for_tot [ s [ i ] ] = cost [ i ] ; } else { for_tot [ s [ i ] ] = for_tot [ s [ i ] ] + cost [ i ] ; } } for ( auto & i : for_max ) { ans += for_tot [ i . first ] - i . second ; } return ans ; } 
vector < string > ReplaceDuplicates ( vector < string > names ) { unordered_map < string , int > hash ; for ( int i = 0 ; i < names . size ( ) ; i ++ ) { if ( hash . find ( names [ i ] ) == hash . end ( ) ) { hash [ names [ i ] ] = 1 ; } else { int count = hash [ names [ i ] ] ; hash [ names [ i ] ] ++ ; names [ i ] += to_string ( count ) ; } } return names ; } 
vector < int > minmaxNumbers ( vector < vector < int > > matrix , vector < int > res ) { unordered_set < int > s ; for ( int i = 0 ; i < matrix . size ( ) ; i ++ ) { int min_r = INT_MAX ; for ( int j = 0 ; j < matrix [ i ] . size ( ) ; j ++ ) { min_r = min ( min_r , matrix [ i ] [ j ] ) ; } s . insert ( min_r ) ; } for ( int j = 0 ; j < matrix [ 0 ] . size ( ) ; j ++ ) { int max_c = INT_MIN ; for ( int i = 0 ; i < matrix . size ( ) ; i ++ ) { max_c = max ( max_c , matrix [ i ] [ j ] ) ; } if ( s . find ( max_c ) != s . end ( ) ) { res . push_back ( max_c ) ; } } return res ; } 
int LengthOfLongestAp ( vector < int > a , int n ) { unordered_map < int , unordered_map < int , int > > dp ; int res = 2 ; for ( int i = 0 ; i < n ; ++ i ) { for ( int j = i + 1 ; j < n ; ++ j ) { int d = a [ j ] - a [ i ] ; if ( dp . find ( d ) != dp . end ( ) ) { if ( dp [ d ] . find ( i ) != dp [ d ] . end ( ) ) { dp [ d ] [ j ] = dp [ d ] [ i ] + 1 ; } else { dp [ d ] [ j ] = 2 ; } } else { dp [ d ] = unordered_map < int , int > ( ) ; dp [ d ] [ j ] = 2 ; } res = max ( res , dp [ d ] [ j ] ) ; } } return res ; } 
char FindKthChar ( int n , int k ) { string prev = "A" ; string cur ; if ( n == 1 ) { return 'A' ; } for ( int j = 2 ; j <= n ; j ++ ) { cur = prev + "B" ; for ( int i = 0 ; i < prev . length ( ) ; i ++ ) { if ( prev [ i ] == 'A' ) { prev [ i ] = 'B' ; } else { prev [ i ] = 'A' ; } } reverse ( prev . begin ( ) , prev . end ( ) ) ; cur += prev ; prev = cur ; } return cur [ k - 1 ] ; } 
char FindKthLargest ( string s , int k ) { string tmp = s ; sort ( tmp . begin ( ) , tmp . end ( ) ) ; reverse ( tmp . begin ( ) , tmp . end ( ) ) ; return tmp [ k - 1 ] ; } 
int SubArraylen ( vector < int > arr , int n , int k ) { unordered_map < int , int > mp ; mp [ arr [ 0 ] ] = 0 ; for ( int i = 1 ; i < n ; i ++ ) { arr [ i ] = arr [ i ] + arr [ i - 1 ] ; mp [ arr [ i ] ] = i ; } int length = INT_MAX ; for ( int i = 0 ; i < n ; i ++ ) { if ( arr [ i ] < k ) { continue ; } else { int x = arr [ i ] - k ; if ( x == 0 ) { length = min ( length , i ) ; } if ( mp . find ( x ) == mp . end ( ) ) { continue ; } else { length = min ( length , i - mp [ x ] ) ; } } } return length ; } 
int FindMaxLen ( vector < int > a , int k ) { int n = a . size ( ) ; sort ( a . begin ( ) , a . end ( ) ) ; vector < bool > vis ( n , false ) ; map < int , int > mp ; for ( int i = 0 ; i < n ; i ++ ) { mp [ a [ i ] ] = i ; } int c = 0 ; for ( int i = 0 ; i < n ; ++ i ) { if ( ! vis [ i ] ) { int check = a [ i ] * k ; if ( mp . find ( check ) != mp . end ( ) ) { c ++ ; vis [ mp [ check ] ] = true ; } } } return n - c ; } 
vector < int > MinDistancePoints ( vector < int > a , int k , int n ) { map < int , int > m ; queue < int > q ; for ( int i = 0 ; i < n ; ++ i ) { m [ a [ i ] ] = 1 ; q . push ( a [ i ] ) ; } vector < int > ans ; while ( k > 0 ) { int x = q . front ( ) ; q . pop ( ) ; if ( m . find ( x - 1 ) == m . end ( ) && k > 0 ) { m [ x - 1 ] = 1 ; q . push ( x - 1 ) ; ans . push_back ( x - 1 ) ; k -- ; } if ( ! m [ x + 1 ] && k > 0 ) { m [ x + 1 ] = 1 ; q . push ( x + 1 ) ; ans . push_back ( x + 1 ) ; k -- ; } } return ans ; } 
bool IsValidLen ( string s , int length , int k ) { int n = s . size ( ) ; unordered_map < char , int > mp ; int right = 0 ; while ( right < length ) { if ( mp . find ( s [ right ] ) != mp . end ( ) ) { mp [ s [ right ] ] ++ ; } else { mp [ s [ right ] ] = 1 ; } right ++ ; } if ( mp . size ( ) <= k ) { return true ; } while ( right < n ) { if ( mp . find ( s [ right ] ) != mp . end ( ) ) { mp [ s [ right ] ] ++ ; } else { mp [ s [ right ] ] = 1 ; } if ( mp . find ( s [ right - length ] ) != mp . end ( ) ) { mp [ s [ right - length ] ] -- ; } if ( mp [ s [ right - length ] ] == 0 ) { mp . erase ( s [ right - length ] ) ; } if ( mp . size ( ) <= k ) { return true ; } right ++ ; } return mp . size ( ) <= k ; } 
int Partition ( vector < int > arr , int low , int high ) { int pivot = arr [ high ] ; int i = ( low - 1 ) ; for ( int j = low ; j <= high - 1 ; j ++ ) { if ( arr [ j ] <= pivot ) { i ++ ; swap ( arr [ i ] , arr [ j ] ) ; } } swap ( arr [ i + 1 ] , arr [ high ] ) ; return i + 1 ; } 
int StrScore ( vector < string > strs , string s , int n ) { unordered_map < string , int > m ; for ( int i = 0 ; i < n ; i ++ ) { m [ strs [ i ] ] = i + 1 ; } if ( m . find ( s ) == m . end ( ) ) { return 0 ; } int score = 0 ; for ( int i = 0 ; i < s . length ( ) ; i ++ ) { score += s [ i ] - 'a' + 1 ; } score = score * m [ s ] ; return score ; } 
vector < int > CountEle ( vector < int > s , vector < int > a , int n ) { unordered_map < int , bool > mp ; vector < int > ans ; for ( int i = 0 ; i < n ; ++ i ) { int num = a [ i ] ; if ( mp . find ( num ) != mp . end ( ) ) { ans . push_back ( 0 ) ; } else { int cnt = 0 ; while ( s [ 0 ] != num ) { mp [ s [ 0 ] ] = true ; s . erase ( s . begin ( ) ) ; cnt ++ ; } s . erase ( s . begin ( ) ) ; cnt ++ ; ans . push_back ( cnt ) ; } } return ans ; } 
int MaxDistinctChar ( string s , int n , int k ) { unordered_map < char , int > freq ; for ( int i = 0 ; i < n ; i ++ ) { freq [ s [ i ] ] ++ ; } vector < int > v ; for ( auto & it : freq ) { v . push_back ( it . second ) ; } sort ( v . begin ( ) , v . end ( ) ) ; for ( int i = 0 ; i < v . size ( ) ; i ++ ) { int mn = min ( v [ i ] - 1 , k ) ; v [ i ] -= mn ; k -= mn ; } if ( k > 0 ) { for ( int i = 0 ; i < v . size ( ) ; i ++ ) { int mn = min ( v [ i ] , k ) ; v [ i ] -= mn ; k -= mn ; } } int res = 0 ; for ( int i = 0 ; i < v . size ( ) ; i ++ ) { if ( v [ i ] == 1 ) { res ++ ; } } return res ; } 
int FindKth ( vector < int > arr , int n , int k ) { unordered_set < int > missing ; int count = 0 ; for ( int i = 0 ; i < n ; i ++ ) { missing . insert ( arr [ i ] ) ; } int max_m = * max_element ( arr . begin ( ) , arr . end ( ) ) ; int min_m = * min_element ( arr . begin ( ) , arr . end ( ) ) ; for ( int i = min_m + 1 ; i < max_m ; i ++ ) { if ( missing . find ( i ) == missing . end ( ) ) { count ++ ; } if ( count == k ) { return i ; } } return -1 ; } 
bool AlmostSort ( vector < int > a , int n ) { for ( int i = 0 ; i < n - 1 ; i ++ ) { if ( a [ i ] > a [ i + 1 ] ) { swap ( a [ i ] , a [ i + 1 ] ) ; i ++ ; } } for ( int i = 0 ; i < n - 1 ; i ++ ) { if ( a [ i ] > a [ i + 1 ] ) { return false ; } } return true ; } 
int MaximumSum ( string s , int n , int k ) { int sum = 0 ; vector < int > freq ( 256 ) ; for ( int i = 0 ; i < n ; i ++ ) { freq [ s [ i ] ] ++ ; } sort ( freq . begin ( ) , freq . end ( ) , greater < > ( ) ) ; for ( int i = 0 ; i < 256 ; i ++ ) { if ( k > freq [ i ] ) { sum += freq [ i ] * freq [ i ] ; k -= freq [ i ] ; } else { sum += freq [ i ] * k ; break ; } } return sum ; } 
int FindMinOperations ( vector < int > arr , int n , int k ) { int operations = 0 ; for ( int i = 0 ; i < k ; i ++ ) { unordered_map < int , int > freq ; for ( int j = i ; j < n ; j += k ) { freq [ arr [ j ] ] ++ ; } int max1 = 0 , num = 0 ; for ( auto & [ key , value ] : freq ) { if ( value > max1 ) { max1 = value ; num = key ; } } for ( auto & [ key , value ] : freq ) { if ( key != num ) { operations += value ; } } } return operations ; } 
vector < string > SubString ( string s , int n ) { vector < string > v ; for ( int i = 0 ; i < n ; i ++ ) { for ( int length = 1 ; length <= n - i ; length ++ ) { string find = s . substr ( i , length ) ; v . push_back ( find ) ; } } return v ; } 
bool CheckUniqueFrequency ( vector < int > arr , int n ) { unordered_map < int , int > freq ; for ( int i = 0 ; i < n ; i ++ ) { freq [ arr [ i ] ] ++ ; } unordered_set < int > unique_freq ; for ( auto & [ key , value ] : freq ) { if ( unique_freq . find ( value ) != unique_freq . end ( ) ) { return false ; } else { unique_freq . insert ( value ) ; } } return true ; } 
int MinCost ( string str1 , string str2 , int n ) { int cost = 0 ; string tmp = str1 ; for ( int i = 0 ; i < n ; i ++ ) { if ( tmp [ i ] != str2 [ i ] ) { if ( i < n - 1 && tmp [ i + 1 ] != str2 [ i + 1 ] ) { swap ( tmp [ i ] , tmp [ i + 1 ] ) ; cost ++ ; } else { cost ++ ; } } } return cost ; } 
bool IsValidNum ( string x ) { map < int , int > mp ; for ( int i = 0 ; i < x . length ( ) ; i ++ ) { if ( mp . find ( x [ i ] - '0' ) != mp . end ( ) ) { return false ; } else if ( x [ i ] - '0' > 5 ) { return false ; } else { mp [ x [ i ] - '0' ] = 1 ; } } return true ; } 
int MinimizeDiff ( vector < int > arr , int n , int k ) { int max = * max_element ( arr . begin ( ) , arr . end ( ) ) ; int min = * min_element ( arr . begin ( ) , arr . end ( ) ) ; if ( max - min <= k ) { return max - min ; } int avg = ( max + min ) / 2 ; for ( int i = 0 ; i < n ; i ++ ) { if ( arr [ i ] > avg ) { arr [ i ] -= k ; } else { arr [ i ] += k ; } } max = * max_element ( arr . begin ( ) , arr . end ( ) ) ; min = * min_element ( arr . begin ( ) , arr . end ( ) ) ; return max - min ; } 
int GetMinCost ( vector < int > arr , int n ) { int min_ele = * min_element ( arr . begin ( ) , arr . end ( ) ) ; return min_ele * ( n - 1 ) ; } 
bool Possibility ( unordered_map < int , int > m , int length , string s ) { int count_odd = 0 ; for ( int i = 0 ; i < length ; i ++ ) { if ( m [ s [ i ] - '0' ] & 1 ) { count_odd ++ ; } if ( count_odd > 1 ) { return false ; } } return true ; } 
int MinimumCostOfBreaking ( vector < int > x , vector < int > y , int m , int n ) { int res = 0 ; sort ( x . begin ( ) , x . end ( ) , greater < > ( ) ) ; sort ( y . begin ( ) , y . end ( ) , greater < > ( ) ) ; int hzntl = 1 , vert = 1 ; int i = 0 , j = 0 ; while ( i < m && j < n ) { if ( x [ i ] > y [ j ] ) { res += x [ i ] * vert ; hzntl ++ ; i ++ ; } else { res += y [ j ] * hzntl ; vert ++ ; j ++ ; } } int total = 0 ; while ( i < m ) { total += x [ i ++ ] ; } res += total * vert ; total = 0 ; while ( j < n ) { total += y [ j ++ ] ; } res += total * hzntl ; return res ; } 
int FindMaximumScore ( vector < int > a , int n ) { unordered_map < int , int > freq ; for ( int i = 0 ; i < n ; i ++ ) { if ( freq . find ( a [ i ] ) != freq . end ( ) ) { freq [ a [ i ] ] = freq [ a [ i ] ] + 1 ; } else { freq [ a [ i ] ] = 1 ; } } vector < int > dp ( * max_element ( a . begin ( ) , a . end ( ) ) + 1 , 0 ) ; dp [ 0 ] = 0 ; dp [ 1 ] = freq [ 1 ] ; for ( int i = 2 ; i < dp . size ( ) ; i ++ ) { dp [ i ] = max ( dp [ i - 1 ] , dp [ i - 2 ] + freq [ i ] * i ) ; } return dp [ dp . size ( ) - 1 ] ; } 
int CountWays ( string s , string t , int k , int mod ) { int n = s . size ( ) ; int a = 0 , b = 0 ; for ( int i = 0 ; i < n ; i ++ ) { string p = s . substr ( i , n - i ) + s . substr ( 0 , i ) ; if ( p == t ) { a ++ ; } else { b ++ ; } } vector < int > dp1 ( k + 1 ) , dp2 ( k + 1 ) ; if ( s == t ) { dp1 [ 0 ] = 1 ; dp2 [ 0 ] = 0 ; } else { dp1 [ 0 ] = 0 ; dp2 [ 0 ] = 1 ; } for ( int i = 1 ; i <= k ; i ++ ) { dp1 [ i ] = ( ( dp1 [ i - 1 ] * ( a - 1 ) ) % mod + ( dp2 [ i - 1 ] * a ) % mod ) % mod ; dp2 [ i ] = ( ( dp1 [ i - 1 ] * ( b ) ) % mod + ( dp2 [ i - 1 ] * ( b - 1 ) ) % mod ) % mod ; } return dp1 [ k ] ; } 
int FindSubarraySum ( vector < int > arr , int n , int k ) { unordered_map < int , int > prev_sum ; int res = 0 ; int curr_sum = 0 ; for ( int i = 0 ; i < n ; i ++ ) { curr_sum += arr [ i ] ; if ( curr_sum == k ) { res ++ ; } if ( prev_sum . find ( curr_sum - k ) != prev_sum . end ( ) ) { res += prev_sum [ curr_sum - k ] ; } prev_sum [ curr_sum ] ++ ; } return res ; } 
int MaximumOccurrence ( string s ) { int n = s . length ( ) ; map < string , int > freq ; for ( int i = 0 ; i < n ; i ++ ) { string temp ; temp += s [ i ] ; freq [ temp ] ++ ; } for ( int i = 0 ; i < n ; i ++ ) { for ( int j = i + 1 ; j < n ; j ++ ) { string temp ; temp += s [ i ] ; temp += s [ j ] ; freq [ temp ] ++ ; } } int answer = INT_MIN ; for ( auto entry : freq ) { answer = max ( answer , entry . second ) ; } return answer ; } 
int CountCharacters ( vector < string > strings , string chars ) { int res = 0 ; unordered_map < char , int > freq ; for ( int i = 0 ; i < chars . length ( ) ; i ++ ) { freq [ chars [ i ] ] += 1 ; } for ( string & st : strings ) { bool flag = true ; for ( char c : st ) { if ( freq . find ( c ) == freq . end ( ) ) { flag = false ; break ; } } if ( flag ) { res += st . length ( ) ; } } return res ; } 
int DistinctSubstring ( string p , string q , int k , int n ) { unordered_set < string > ss ; for ( int i = 0 ; i < n ; ++ i ) { int sum = 0 ; string s ; for ( int j = i ; j < n ; ++ j ) { int pos = p [ j ] - 'a' ; sum += q [ pos ] - '0' ; s += p [ j ] ; if ( sum <= k ) { ss . insert ( s ) ; } else { break ; } } } return ss . size ( ) ; } 
int UniqueMorseRep ( vector < string > arr ) { vector < string > morseCode = { ".-" , "-..." , "-.-." , "-.." , "." , "..-." , "--." , "...." , ".." , ".---" , "-.-" , ".-.." , "--" , "-." , "---" , ".--." , "--.-" , ".-." , "..." , "-" , "..-" , "...-" , ".--" , "-..-" , "-.--" , "--.." } ; unordered_set < string > st ; int n = arr . size ( ) ; for ( int i = 0 ; i < n ; i ++ ) { string temp ; int m = arr [ i ] . length ( ) ; for ( int j = 0 ; j < m ; j ++ ) { temp += morseCode [ arr [ i ] [ j ] - 'a' ] ; } st . insert ( temp ) ; } return st . size ( ) ; } 
int CountSubstrings ( string st , int k ) { int n = st . size ( ) ; int answer = 0 ; unordered_map < char , int > map ; for ( int i = 0 ; i < k ; i ++ ) { if ( map . find ( st [ i ] ) == map . end ( ) ) { map [ st [ i ] ] = 1 ; } else { map [ st [ i ] ] ++ ; } } if ( map . size ( ) == k ) { answer ++ ; } for ( int i = k ; i < n ; i ++ ) { if ( map . find ( st [ i ] ) == map . end ( ) ) { map [ st [ i ] ] = 1 ; } else { map [ st [ i ] ] ++ ; } map [ st [ i - k ] ] -- ; if ( map [ st [ i - k ] ] == 0 ) { map . erase ( st [ i - k ] ) ; } if ( map . size ( ) == k ) { answer ++ ; } } return answer ; } 
bool CanConstruct ( string s , int k ) { map < int , int > m ; int i = 0 , j = 0 , p = 0 ; if ( s . length ( ) == k ) { return true ; } for ( i = 0 ; i < s . length ( ) ; i ++ ) { m [ s [ i ] ] = m [ s [ i ] ] + 1 ; } if ( k > s . length ( ) ) { return false ; } else { for ( auto & h : m ) { if ( h . second % 2 != 0 ) { p = p + 1 ; } } } if ( k < p ) { return false ; } return true ; } 
bool EqualIgnoreCase ( string str1 , string str2 ) { transform ( str1 . begin ( ) , str1 . end ( ) , str1 . begin ( ) , :: toupper ) ; transform ( str2 . begin ( ) , str2 . end ( ) , str2 . begin ( ) , :: toupper ) ; return str1 == str2 ; } 
int FindLongestSub ( string bin ) { int n = bin . length ( ) , i ; int sum = 0 ; unordered_map < int , int > prev_sum ; int max_len = 0 ; for ( i = 0 ; i < n ; i ++ ) { if ( bin [ i ] == '1' ) { sum ++ ; } else { sum -- ; } if ( sum > 0 ) { max_len = i + 1 ; } else if ( sum <= 0 ) { if ( prev_sum . find ( sum - 1 ) != prev_sum . end ( ) ) { int curr_len = i - prev_sum [ sum - 1 ] ; max_len = max ( max_len , curr_len ) ; } } if ( prev_sum . find ( sum ) == prev_sum . end ( ) ) { prev_sum [ sum ] = i ; } } return max_len ; } 
bool HasAllCodes ( string s , int k ) { unordered_set < string > us ; for ( int i = 0 ; i + k <= s . size ( ) ; i ++ ) { us . insert ( s . substr ( i , k ) ) ; } return us . size ( ) == 1 << k ; } 
bool CheckPalin ( string word ) { int n = word . length ( ) ; transform ( word . begin ( ) , word . end ( ) , word . begin ( ) , :: tolower ) ; for ( int i = 0 ; i < n ; i ++ , n -- ) { if ( word [ i ] != word [ n - 1 ] ) { return false ; } } return true ; } 
string Convert ( string st ) { string w , z ; transform ( st . begin ( ) , st . end ( ) , st . begin ( ) , :: toupper ) ; st += " " ; for ( int i = 0 ; i < st . length ( ) ; i ++ ) { char ch = st [ i ] ; if ( ch != ' ' ) { w += ch ; } else { z += char ( tolower ( w [ 0 ] ) ) + w . substr ( 1 ) + " " ; w = "" ; } } return z ; } 
int MaxLines ( int n , vector < int > x1 , vector < int > y1 , vector < int > x2 , vector < int > y2 ) { unordered_set < double > s ; double slope ; for ( int i = 0 ; i < n ; ++ i ) { if ( x1 [ i ] == x2 [ i ] ) { slope = INT_MAX ; } else { slope = ( y2 [ i ] - y1 [ i ] ) * 1.0 / ( x2 [ i ] - x1 [ i ] ) ; } s . insert ( slope ) ; } return s . size ( ) ; } 
unordered_map < int , int > PrimeFactor ( int n ) { unordered_map < int , int > primef ; while ( n % 2 == 0 ) { if ( primef . find ( 2 ) != primef . end ( ) ) { primef [ 2 ] += 1 ; } else { primef [ 2 ] = 1 ; } n /= 2 ; } for ( int i = 3 ; i <= sqrt ( n ) ; i ++ ) { while ( n % i == 0 ) { if ( primef . find ( i ) != primef . end ( ) ) { primef [ i ] += 1 ; } else { primef [ i ] = 1 ; } n /= i ; } } if ( n > 2 ) { primef [ n ] = 1 ; } return primef ; } 
string IsDivisibleByDivisor ( int s , int d ) { s %= d ; unordered_set < int > hash_map ; hash_map . insert ( s ) ; for ( int i = 0 ; i <= d ; i ++ ) { s += s % d ; s %= d ; if ( hash_map . find ( s ) != hash_map . end ( ) ) { if ( s == 0 ) { return "Yes" ; } return "No" ; } else { hash_map . insert ( s ) ; } } return "Yes" ; } 
bool OddSum ( vector < int > a , int n , int k ) { set < int > odd ; set < int > even ; for ( int i = 0 ; i < n ; i ++ ) { if ( a [ i ] % 2 == 0 ) { even . insert ( a [ i ] ) ; } else { odd . insert ( a [ i ] ) ; } } if ( odd . size ( ) >= k ) { return true ; } bool flag = false ; for ( int i = 1 ; i < k ; i += 2 ) { int needed = k - i ; if ( needed <= even . size ( ) ) { return true ; } } return flag ; } 
int DayOfYear ( string date ) { vector < int > days { 31 , 28 , 31 , 30 , 31 , 30 , 31 , 31 , 30 , 31 , 30 , 31 } ; int year = stoi ( date . substr ( 0 , 4 ) ) ; int month = stoi ( date . substr ( 5 , 2 ) ) ; int day = stoi ( date . substr ( 8 ) ) ; if ( month > 2 && year % 4 == 0 && ( year % 100 != 0 || year % 400 == 0 ) ) { ++ day ; } while ( month > 1 ) { day = day + days [ month - 2 ] ; -- month ; } return day ; } 
bool IsPerfectSquare ( vector < int > arr , int n ) { unordered_map < int , int > umap ; for ( int i = 0 ; i < n ; i ++ ) { umap [ arr [ i ] ] ++ ; } for ( auto & itr : umap ) { if ( itr . second % 2 == 1 ) { return false ; } } return true ; } 
int MinMoves ( int n ) { string s = to_string ( n ) ; int ans = INT_MAX ; int length = s . size ( ) ; for ( int i = 0 ; i < length ; ++ i ) { for ( int j = 0 ; j < length ; ++ j ) { if ( i == j ) { continue ; } string t = s ; int cur = 0 ; for ( int k = i ; k < length - 1 ; ++ k ) { swap ( t [ k ] , t [ k + 1 ] ) ; ++ cur ; } for ( int k = j - ( j > i ) ; k < length - 2 ; ++ k ) { swap ( t [ k ] , t [ k + 1 ] ) ; ++ cur ; } int pos = -1 ; for ( int k = 0 ; k < length ; ++ k ) { if ( t [ k ] != '0' ) { pos = k ; break ; } } for ( int k = pos ; k > 0 ; -- k ) { swap ( t [ k ] , t [ k - 1 ] ) ; ++ cur ; } int nn = stoi ( t ) ; if ( nn % 25 == 0 ) { ans = min ( ans , cur ) ; } } } if ( ans == INT_MAX ) { return -1 ; } return ans ; } 
int MinimumOperations ( vector < int > a , int n ) { unordered_map < int , int > mp ; for ( int i = 0 ; i < n ; i ++ ) { mp [ a [ i ] ] += 1 ; } int count = 0 ; for ( auto & entry : mp ) { if ( entry . second > 1 ) { count += entry . second - 1 ; } } return count ; } 
int KaprekarRec ( int n , int prev ) { if ( n == 0 ) { return 0 ; } prev = n ; int digits [ 4 ] ; for ( int i = 0 ; i < 4 ; i ++ ) { digits [ i ] = n % 10 ; n = n / 10 ; } sort ( digits , digits + 4 ) ; int asc = 0 ; for ( int i = 0 ; i < 4 ; i ++ ) { asc = asc * 10 + digits [ i ] ; } sort ( digits , digits + 4 ) ; int desc = 0 ; for ( int i = 3 ; i >= 0 ; i -- ) { desc = desc * 10 + digits [ i ] ; } int diff = abs ( asc - desc ) ; if ( diff == prev ) { return diff ; } return KaprekarRec ( diff , prev ) ; } 
string FractionToDecimal ( int numr , int denr ) { string res ; map < int , int > mp ; int rem = numr % denr ; while ( rem != 0 && mp . find ( rem ) == mp . end ( ) ) { mp [ rem ] = res . length ( ) ; rem = rem * 10 ; int res_part = rem / denr ; res += to_string ( res_part ) ; rem = rem % denr ; } if ( rem == 0 ) { return "" ; } if ( mp . find ( rem ) != mp . end ( ) ) { return res . substr ( mp [ rem ] ) ; } return "" ; } 
bool IsFancy ( string num ) { map < char , char > fp ; fp [ '0' ] = '0' ; fp [ '1' ] = '1' ; fp [ '6' ] = '9' ; fp [ '8' ] = '8' ; fp [ '9' ] = '6' ; int n = num . length ( ) ; int l = 0 , r = n - 1 ; while ( l <= r ) { if ( fp . find ( num [ l ] ) == fp . end ( ) || fp [ num [ l ] ] != num [ r ] ) { return false ; } l ++ ; r -- ; } return true ; } 
