List < String > separateParenGroups ( String parenString ) { List < String > allParens = new ArrayList < > ( ) ; StringBuilder currentParen = new StringBuilder ( ) ; int currentDepth = 0 ; for ( var c : parenString . toCharArray ( ) ) { if ( c == '(' ) { currentDepth += 1 ; currentParen . append ( c ) ; } else if ( c == ')' ) { currentDepth -= 1 ; currentParen . append ( c ) ; if ( currentDepth == 0 ) { allParens . add ( currentParen . toString ( ) ) ; currentParen . setLength ( 0 ) ; } } } return allParens ; } 
List < Integer > parseNestedParens ( String parenString ) { List < Integer > allLevels = new ArrayList < > ( ) ; int level = 0 ; int maxLevel = 0 ; for ( int i = 0 ; i < parenString . length ( ) ; i ++ ) { char chr = parenString . charAt ( i ) ; if ( chr == '(' ) { level += 1 ; if ( level > maxLevel ) { maxLevel = level ; } } if ( chr == ')' ) { level -= 1 ; if ( level == 0 ) { allLevels . add ( maxLevel ) ; maxLevel = 0 ; } } } return allLevels ; } 
List < String > filterBySubstring ( List < String > strings , String substring ) { List < String > result = new ArrayList < > ( ) ; for ( var s : strings ) { if ( s . contains ( substring ) ) { result . add ( s ) ; } } return result ; } 
List < Integer > rollingMax ( List < Integer > numbers ) { List < Integer > result = new ArrayList < > ( ) ; int runningMax = 0 ; for ( Integer n : numbers ) { if ( n > runningMax ) { runningMax = n ; } result . add ( runningMax ) ; } return result ; } 
String makePalindrome ( String s ) { if ( s . isEmpty ( ) ) { return "" ; } for ( int i = 0 ; i < s . length ( ) ; i ++ ) { String rStr = s . substring ( i ) ; if ( rStr . equals ( new StringBuilder ( rStr ) . reverse ( ) . toString ( ) ) ) { String nStr = s . substring ( 0 , i ) ; String n2Str = new StringBuilder ( nStr ) . reverse ( ) . toString ( ) ; return s + n2Str ; } } return s . substring ( 0 , s . length ( ) - 1 ) + new StringBuilder ( s ) . reverse ( ) . toString ( ) ; } 
String stringXor ( String a , String b ) { StringBuilder result = new StringBuilder ( ) ; for ( int i = 0 ; i < a . length ( ) ; i ++ ) { if ( a . charAt ( i ) == b . charAt ( i ) ) { result . append ( '0' ) ; } else { result . append ( '1' ) ; } } return result . toString ( ) ; } 
String longest ( List < String > strings ) { if ( strings . isEmpty ( ) ) return "" ; int maxLen = strings . stream ( ) . mapToInt ( String :: length ) . max ( ) . getAsInt ( ) ; for ( String s : strings ) { if ( s . length ( ) == maxLen ) { return s ; } } return "" ; } 
String StringSequence ( int n ) { StringBuilder s = new StringBuilder ( ) ; for ( int i = 0 ; i < n ; i ++ ) { s . append ( i ) ; s . append ( " " ) ; } s . append ( n ) ; return s . toString ( ) ; } 
int countDistinctCharacters ( String s ) { Set < Character > distinct = new HashSet < > ( ) ; for ( char c : s . toLowerCase ( ) . toCharArray ( ) ) { distinct . add ( c ) ; } return distinct . size ( ) ; } 
int howManyTimes ( String s , String sub ) { int times = 0 ; for ( int i = 0 ; i <= s . length ( ) - sub . length ( ) ; i ++ ) { if ( s . startsWith ( sub , i ) ) { times += 1 ; } } return times ; } 
String sortNumbers ( String numbers ) { Map < String , Integer > toNum = Map . of ( "zero" , 0 , "one" , 1 , "two" , 2 , "three" , 3 , "four" , 4 , "five" , 5 , "six" , 6 , "seven" , 7 , "eight" , 8 , "nine" , 9 ) ; Map < Integer , String > fromNum = Map . of ( 0 , "zero" , 1 , "one" , 2 , "two" , 3 , "three" , 4 , "four" , 5 , "five" , 6 , "six" , 7 , "seven" , 8 , "eight" , 9 , "nine" ) ; List < Integer > ints = new ArrayList < > ( ) ; StringBuilder current = new StringBuilder ( ) ; for ( int i = 0 ; i <= numbers . length ( ) ; i ++ ) { if ( i == numbers . length ( ) || numbers . charAt ( i ) == ' ' ) { if ( toNum . containsKey ( current . toString ( ) ) ) { ints . add ( toNum . get ( current . toString ( ) ) ) ; current . setLength ( 0 ) ; } } else { current . append ( numbers . charAt ( i ) ) ; } } Collections . sort ( ints ) ; StringBuilder result = new StringBuilder ( ) ; for ( int i = 0 ; i < ints . size ( ) ; i ++ ) { result . append ( fromNum . get ( ints . get ( i ) ) ) ; if ( i != ints . size ( ) - 1 ) { result . append ( " " ) ; } } return result . toString ( ) ; } 
List < Double > findClosestElements ( List < Double > numbers ) { List < Double > closestPair = new ArrayList < > ( Arrays . asList ( numbers . get ( 0 ) , numbers . get ( 1 ) ) ) ; double distance = Math . abs ( numbers . get ( 0 ) - numbers . get ( 1 ) ) ; for ( int i = 0 ; i < numbers . size ( ) ; i ++ ) { for ( int j = i + 1 ; j < numbers . size ( ) ; j ++ ) { if ( Math . abs ( numbers . get ( i ) - numbers . get ( j ) ) < distance ) { closestPair . set ( 0 , numbers . get ( i ) ) ; closestPair . set ( 1 , numbers . get ( j ) ) ; distance = Math . abs ( numbers . get ( i ) - numbers . get ( j ) ) ; } } } Collections . sort ( closestPair ) ; return closestPair ; } 
List < Double > rescaleToUnit ( List < Double > numbers ) { double minNum = Collections . min ( numbers ) ; double maxNum = Collections . max ( numbers ) ; List < Double > result = new ArrayList < > ( ) ; for ( double n : numbers ) { result . add ( ( n - minNum ) / ( maxNum - minNum ) ) ; } return result ; } 
List < Integer > filterIntegers ( List < Object > values ) { List < Integer > result = new ArrayList < > ( ) ; for ( var e : values ) { if ( e instanceof Integer ) { result . add ( ( Integer ) e ) ; } } return result ; }
List < Integer > removeDuplicates ( List < Integer > numbers ) { Map < Integer , Integer > c = new HashMap < > ( ) ; for ( int i : numbers ) { c . put ( i , c . getOrDefault ( i , 0 ) + 1 ) ; } List < Integer > result = new ArrayList < > ( ) ; for ( int i : numbers ) { if ( c . get ( i ) == 1 ) { result . add ( i ) ; } } return result ; } 
String flipCase ( String s ) { StringBuilder result = new StringBuilder ( ) ; for ( char c : s . toCharArray ( ) ) { if ( Character . isLowerCase ( c ) ) { result . append ( Character . toUpperCase ( c ) ) ; } else { result . append ( Character . toLowerCase ( c ) ) ; } } return result . toString ( ) ; } 
List < String > filterByPrefix ( List < String > strings , String prefix ) { List < String > result = new ArrayList < > ( ) ; for ( int i = 0 ; i < strings . size ( ) ; i ++ ) { if ( strings . get ( i ) . startsWith ( prefix ) ) { result . add ( strings . get ( i ) ) ; } } return result ; } 
double findZero ( List < Double > xs ) { double ans = 0 ; double value = 0 ; for ( int i = 0 ; i < xs . size ( ) ; i ++ ) { value += xs . get ( i ) * Math . pow ( ans , i ) ; } while ( Math . abs ( value ) > 1e-6 ) { double driv = 0 ; for ( int i = 1 ; i < xs . size ( ) ; i ++ ) { driv += xs . get ( i ) * Math . pow ( ans , i - 1 ) * i ; } ans -= value / driv ; value = 0 ; for ( int i = 0 ; i < xs . size ( ) ; i ++ ) { value += xs . get ( i ) * Math . pow ( ans , i ) ; } } return ans ; } 
List < Integer > sortThird ( List < Integer > l ) { List < Integer > thirds = new ArrayList < > ( ) ; for ( int i = 0 ; i < l . size ( ) ; i += 3 ) { thirds . add ( l . get ( i ) ) ; } Collections . sort ( thirds ) ; List < Integer > result = new ArrayList < > ( ) ; for ( int i = 0 ; i < l . size ( ) ; i ++ ) { if ( i % 3 == 0 ) { result . add ( thirds . get ( i / 3 ) ) ; } else { result . add ( l . get ( i ) ) ; } } return result ; } 
List < Integer > unique ( List < Integer > l ) { List < Integer > result = new ArrayList < > ( new HashSet < > ( l ) ) ; Collections . sort ( result ) ; return result ; } 
double maxElement ( List < Double > l ) { return Collections . max ( l ) ; } 
boolean triplesSumToZero ( List < Integer > l ) { for ( int i = 0 ; i < l . size ( ) ; i ++ ) { for ( int j = i + 1 ; j < l . size ( ) ; j ++ ) { for ( int k = j + 1 ; k < l . size ( ) ; k ++ ) { if ( l . get ( i ) + l . get ( j ) + l . get ( k ) == 0 ) { return true ; } } } } return false ; } 
int fib4 ( int n ) { List < Integer > results = new ArrayList < > ( Arrays . asList ( 0 , 0 , 2 , 0 ) ) ; for ( int i = 4 ; i <= n ; i ++ ) { results . add ( results . get ( i - 4 ) + results . get ( i - 3 ) + results . get ( i - 2 ) + results . get ( i - 1 ) ) ; } return results . get ( n ) ; } 
boolean isPalindrome ( String text ) { String pr = new StringBuilder ( text ) . reverse ( ) . toString ( ) ; return pr . equals ( text ) ; } 
String removeVowels ( String text ) { StringBuilder result = new StringBuilder ( ) ; String vowels = "aeiou" ; for ( char ch : text . toCharArray ( ) ) { if ( vowels . indexOf ( Character . toLowerCase ( ch ) ) == - 1 ) { result . append ( ch ) ; } } return result . toString ( ) ; } 
boolean sameChars ( String s0 , String s1 ) { Set < Character > set0 = new HashSet < > ( ) ; for ( char c : s0 . toCharArray ( ) ) { set0 . add ( c ) ; } Set < Character > set1 = new HashSet < > ( ) ; for ( char c : s1 . toCharArray ( ) ) { set1 . add ( c ) ; } return set0 . equals ( set1 ) ; } 
List < Integer > common ( List < Integer > l1 , List < Integer > l2 ) { Set < Integer > us = new HashSet < > ( ) ; for ( int e1 : l1 ) { for ( int e2 : l2 ) { if ( e1 == e2 ) { us . add ( e1 ) ; } } } List < Integer > ret = new ArrayList < > ( us ) ; Collections . sort ( ret ) ; return ret ; } 
boolean correctBracketing ( String brackets ) { int depth = 0 ; for ( char b : brackets . toCharArray ( ) ) { if ( b == '(' ) { depth += 1 ; } if ( b == ')' ) { depth -= 1 ; } if ( depth < 0 ) { return false ; } } return depth == 0 ; } 
String circularShift ( int x , int shift ) { String xs = String . valueOf ( x ) ; if ( shift > xs . length ( ) ) { return new StringBuilder ( xs ) . reverse ( ) . toString ( ) ; } return xs . substring ( xs . length ( ) - shift ) + xs . substring ( 0 , xs . length ( ) - shift ) ; } 
int search ( List < Integer > lst ) { Map < Integer , Integer > counter = new HashMap < > ( ) ; for ( int i : lst ) { counter . put ( i , counter . getOrDefault ( i , 0 ) + 1 ) ; } int ans = - 1 ; for ( var item : counter . entrySet ( ) ) { if ( item . getValue ( ) >= item . getKey ( ) && item . getKey ( ) > ans ) { ans = item . getKey ( ) ; } } return ans ; } 
int smallestChange ( List < Integer > arr ) { int ans = 0 ; for ( int i = 0 ; i < arr . size ( ) / 2 ; i ++ ) { if ( ! arr . get ( i ) . equals ( arr . get ( arr . size ( ) - i - 1 ) ) ) { ans += 1 ; } } return ans ; } 
List < String > totalMatch ( List < String > lst1 , List < String > lst2 ) { int sum1 = 0 ; for ( var st : lst1 ) { sum1 += st . length ( ) ; } int sum2 = 0 ; for ( String st : lst2 ) { sum2 += st . length ( ) ; } return sum1 > sum2 ? lst2 : lst1 ; } 
boolean isHappy ( String s ) { if ( s . length ( ) < 3 ) { return false ; } for ( int i = 0 ; i < s . length ( ) - 2 ; i ++ ) { if ( s . charAt ( i ) == s . charAt ( i + 1 ) || s . charAt ( i ) == s . charAt ( i + 2 ) || s . charAt ( i + 1 ) == s . charAt ( i + 2 ) ) { return false ; } } return true ; } 
List < String > numericalLetterGrade ( List < Double > grades ) { List < String > letterGrade = new ArrayList < > ( ) ; for ( double gpa : grades ) { if ( gpa == 4.0 ) { letterGrade . add ( "A+" ) ; } else if ( gpa > 3.7 ) { letterGrade . add ( "A" ) ; } else if ( gpa > 3.3 ) { letterGrade . add ( "A-" ) ; } else if ( gpa > 3.0 ) { letterGrade . add ( "B+" ) ; } else if ( gpa > 2.7 ) { letterGrade . add ( "B" ) ; } else if ( gpa > 2.3 ) { letterGrade . add ( "B-" ) ; } else if ( gpa > 2.0 ) { letterGrade . add ( "C+" ) ; } else if ( gpa > 1.7 ) { letterGrade . add ( "C" ) ; } else if ( gpa > 1.3 ) { letterGrade . add ( "C-" ) ; } else if ( gpa > 1.0 ) { letterGrade . add ( "D+" ) ; } else if ( gpa > 0.7 ) { letterGrade . add ( "D" ) ; } else if ( gpa > 0.0 ) { letterGrade . add ( "D-" ) ; } else { letterGrade . add ( "E" ) ; } } return letterGrade ; } 
String solve ( int n ) { StringBuilder biStr = new StringBuilder ( ) ; int sum = 0 ; for ( char c : String . valueOf ( n ) . toCharArray ( ) ) { sum += c - '0' ; } while ( sum > 0 ) { biStr . insert ( 0 , sum % 2 ) ; sum /= 2 ; } return biStr . toString ( ) ; } 
String antiShuffle ( String s ) { StringBuilder ret = new StringBuilder ( ) ; StringBuilder current = new StringBuilder ( ) ; for ( int i = 0 ; i <= s . length ( ) ; i ++ ) { if ( i == s . length ( ) || s . charAt ( i ) == ' ' ) { char [ ] tmp = current . toString ( ) . toCharArray ( ) ; Arrays . sort ( tmp ) ; if ( ! ret . isEmpty ( ) ) { ret . append ( ' ' ) ; } ret . append ( String . valueOf ( tmp ) ) ; current . setLength ( 0 ) ; } else { current . append ( s . charAt ( i ) ) ; } } return ret . toString ( ) ; } 
List < Integer > sortArray ( List < Integer > array ) { if ( array . isEmpty ( ) ) { return array ; } if ( ( array . get ( 0 ) + array . get ( array . size ( ) - 1 ) ) % 2 == 1 ) { Collections . sort ( array ) ; } else { array . sort ( Collections . reverseOrder ( ) ) ; } return array ; } 
String encrypt ( String s ) { StringBuilder ans = new StringBuilder ( ) ; for ( char c : s . toCharArray ( ) ) { if ( Character . isLetter ( c ) ) { ans . append ( ( char ) ( 'a' + ( c - 'a' + 4 ) % 26 ) ) ; } else { ans . append ( c ) ; } } return ans . toString ( ) ; } 
int isBored ( String s ) { boolean isStart = true ; int sum = 0 ; for ( int i = 0 ; i < s . length ( ) ; i ++ ) { if ( s . charAt ( i ) == '.' || s . charAt ( i ) == '?' || s . charAt ( i ) == '!' ) { isStart = true ; } else if ( isStart ) { if ( s . charAt ( i ) == ' ' ) { continue ; } if ( s . startsWith ( "I " , i ) ) { sum += 1 ; } isStart = false ; } } return sum ; } 
String encode ( String message ) { String vowels = "aeiouAEIOU" ; StringBuilder ret = new StringBuilder ( ) ; for ( char c : message . toCharArray ( ) ) { if ( Character . isUpperCase ( c ) ) { c = Character . toLowerCase ( c ) ; if ( vowels . indexOf ( c ) != - 1 ) { c = ( char ) ( 'a' + ( c - 'a' + 2 ) % 26 ) ; } } else if ( Character . isLowerCase ( c ) ) { c = Character . toUpperCase ( c ) ; if ( vowels . indexOf ( c ) != - 1 ) { c = ( char ) ( 'A' + ( c - 'A' + 2 ) % 26 ) ; } } ret . append ( c ) ; } return ret . toString ( ) ; } 
int skjkasdkd ( List < Integer > lst ) { int largest = 0 ; for ( int n : lst ) { if ( n > largest ) { boolean prime = true ; for ( int i = 2 ; i < n ; i ++ ) { if ( n % i == 0 ) { prime = false ; } } if ( prime ) { largest = n ; } } } int sum = 0 ; String s = String . valueOf ( largest ) ; for ( int i = 0 ; i < s . length ( ) ; i ++ ) { sum += s . charAt ( i ) - '0' ; } return sum ; } 
boolean checkDictCase ( Map < String , String > dict ) { if ( dict . isEmpty ( ) ) { return false ; } int isLower = 0 ; int isUpper = 0 ; for ( var key : dict . keySet ( ) ) { for ( char c : key . toCharArray ( ) ) { if ( Character . isLowerCase ( c ) ) { isLower = 1 ; } else if ( Character . isUpperCase ( c ) ) { isUpper = 1 ; } else { return false ; } } } return isLower + isUpper == 1 ; } 
int multiply ( int a , int b ) { return ( Math . abs ( a ) % 10 ) * ( Math . abs ( b ) % 10 ) ; } 
int countUpper ( String s ) { String uVowel = "AEIOU" ; int count = 0 ; for ( int i = 0 ; i < s . length ( ) ; i += 2 ) { if ( uVowel . indexOf ( s . charAt ( i ) ) != - 1 ) { count += 1 ; } } return count ; } 
List < String > byLength ( List < Integer > arr ) { Map < Integer , String > numTo = Map . of ( 1 , "One" , 2 , "Two" , 3 , "Three" , 4 , "Four" , 5 , "Five" , 6 , "Six" , 7 , "Seven" , 8 , "Eight" , 9 , "Nine" ) ; List < Integer > sortedArr = new ArrayList < > ( arr ) ; sortedArr . sort ( Collections . reverseOrder ( ) ) ; List < String > newArr = new ArrayList < > ( ) ; for ( int n : sortedArr ) { if ( n >= 1 && n <= 9 ) { newArr . add ( numTo . get ( n ) ) ; } } return newArr ; } 
List < Integer > f ( int n ) { int sum = 0 ; int prod = 1 ; List < Integer > result = new ArrayList < > ( ) ; for ( int i = 1 ; i <= n ; i ++ ) { sum += i ; prod *= i ; if ( i % 2 == 0 ) { result . add ( prod ) ; } else { result . add ( sum ) ; } } return result ; } 
List < Integer > evenOddPalindrome ( int n ) { int evenCount = 0 , oddCount = 0 ; for ( int i = 1 ; i <= n ; i ++ ) { String s = String . valueOf ( i ) ; String rStr = new StringBuilder ( s ) . reverse ( ) . toString ( ) ; if ( s . equals ( rStr ) ) { if ( i % 2 == 1 ) { oddCount += 1 ; } else { evenCount += 1 ; } } } return Arrays . asList ( evenCount , oddCount ) ; } 
Map < Character , Integer > histogram ( String test ) { Map < Character , Integer > count = new HashMap < > ( ) ; int max = 0 ; for ( int i = 0 ; i < test . length ( ) ; i ++ ) { if ( test . charAt ( i ) != ' ' ) { count . put ( test . charAt ( i ) , count . getOrDefault ( test . charAt ( i ) , 0 ) + 1 ) ; if ( count . get ( test . charAt ( i ) ) > max ) { max = count . get ( test . charAt ( i ) ) ; } } } Map < Character , Integer > result = new HashMap < > ( ) ; for ( var item : count . entrySet ( ) ) { if ( item . getValue ( ) == max ) { result . put ( item . getKey ( ) , item . getValue ( ) ) ; } } return result ; } 
List < String > reverseDelete ( String s , String c ) { StringBuilder ret = new StringBuilder ( ) ; for ( char ch : s . toCharArray ( ) ) { if ( c . indexOf ( ch ) == - 1 ) { ret . append ( ch ) ; } } String flag = "False" ; if ( ret . toString ( ) . equals ( new StringBuilder ( ret ) . reverse ( ) . toString ( ) ) ) { flag = "True" ; } return Arrays . asList ( ret . toString ( ) , flag ) ; } 
List < Integer > sortArray ( List < Integer > arr ) { List < Integer > bin = new ArrayList < > ( ) ; for ( int i : arr ) { int b = 0 ; int n = Math . abs ( i ) ; while ( n > 0 ) { b += n % 2 ; n /= 2 ; } bin . add ( b ) ; } for ( int i = 0 ; i < arr . size ( ) ; i ++ ) { for ( int j = 1 ; j < arr . size ( ) ; j ++ ) { if ( bin . get ( j ) < bin . get ( j - 1 ) || ( bin . get ( j ) == bin . get ( j - 1 ) && arr . get ( j ) < arr . get ( j - 1 ) ) ) { Collections . swap ( bin , j , j - 1 ) ; Collections . swap ( arr , j , j - 1 ) ; } } } return arr ; } 
String getClosestVowel ( String word ) { String vowels = "AEIOUaeiou" ; for ( int i = word . length ( ) - 2 ; i > 0 ; i -- ) { if ( vowels . indexOf ( word . charAt ( i ) ) != - 1 && vowels . indexOf ( word . charAt ( i + 1 ) ) == - 1 && vowels . indexOf ( word . charAt ( i - 1 ) ) == - 1 ) { return String . valueOf ( word . charAt ( i ) ) ; } } return "" ; } 
String matchParens ( List < String > lst ) { List < String > strings = Arrays . asList ( lst . get ( 0 ) + lst . get ( 1 ) , lst . get ( 1 ) + lst . get ( 0 ) ) ; for ( var l : strings ) { int count = 0 ; for ( char c : l . toCharArray ( ) ) { if ( c == '(' ) { count += 1 ; } else { count -= 1 ; } if ( count < 0 ) { break ; } } if ( count == 0 ) { return "Yes" ; } } return "No" ; } 
List < Integer > maximum ( List < Integer > arr , int k ) { if ( k == 0 ) { return new ArrayList < > ( ) ; } Collections . sort ( arr ) ; return arr . subList ( arr . size ( ) - k , arr . size ( ) ) ; } 
boolean validDate ( String date ) { if ( date . length ( ) != 10 ) { return false ; } for ( int i = 0 ; i < 10 ; i ++ ) { if ( i == 2 || i == 5 ) { if ( date . charAt ( i ) != '-' ) { return false ; } } else if ( ! Character . isDigit ( date . charAt ( i ) ) ) { return false ; } } int month = Integer . parseInt ( date . substring ( 0 , 2 ) ) ; int day = Integer . parseInt ( date . substring ( 3 , 5 ) ) ; int year = Integer . parseInt ( date . substring ( 6 , 10 ) ) ; if ( month < 1 || month > 12 ) { return false ; } if ( day < 1 || day > 31 ) { return false ; } if ( day == 31 && ( month == 4 || month == 6 || month == 9 || month == 11 || month == 2 ) ) { return false ; } if ( day == 30 && month == 2 ) { return false ; } return true ; } 
Object splitWords ( String txt ) { StringBuilder current = new StringBuilder ( ) ; List < String > result = new ArrayList < > ( ) ; if ( txt . indexOf ( ' ' ) != - 1 ) { for ( int i = 0 ; i <= txt . length ( ) ; i ++ ) { if ( i == txt . length ( ) || txt . charAt ( i ) == ' ' ) { if ( current . length ( ) > 0 ) { result . add ( current . toString ( ) ) ; } current . setLength ( 0 ) ; } else { current . append ( txt . charAt ( i ) ) ; } } return result ; } if ( txt . indexOf ( ',' ) != - 1 ) { for ( int i = 0 ; i <= txt . length ( ) ; i ++ ) { if ( i == txt . length ( ) || txt . charAt ( i ) == ',' ) { if ( current . length ( ) > 0 ) { result . add ( current . toString ( ) ) ; } current . setLength ( 0 ) ; } else { current . append ( txt . charAt ( i ) ) ; } } return result ; } int num = 0 ; for ( char c : txt . toCharArray ( ) ) { if ( Character . isLowerCase ( c ) && c % 2 == 0 ) { num += 1 ; } } return Arrays . asList ( String . valueOf ( num ) ) ; } 
List < Integer > tri ( int n ) { if ( n == 0 ) { return Arrays . asList ( 1 ) ; } List < Integer > tris = new ArrayList < > ( Arrays . asList ( 1 , 3 ) ) ; for ( int i = 2 ; i <= n ; i ++ ) { if ( i % 2 == 0 ) { tris . add ( i / 2 + 1 ) ; } else { tris . add ( tris . get ( i - 1 ) + tris . get ( i - 2 ) + ( i + 3 ) / 2 ) ; } } return tris ; } 
boolean checkIfLastCharIsALetter ( String txt ) { if ( txt . isEmpty ( ) ) { return false ; } return Character . isLetter ( txt . charAt ( txt . length ( ) - 1 ) ) && ( txt . length ( ) == 1 || ! Character . isLetter ( txt . charAt ( txt . length ( ) - 2 ) ) ) ; } 
List < Integer > orderByPoints ( List < Integer > nums ) { List < Integer > result = new ArrayList < > ( ) ; for ( int num : nums ) { String w = String . valueOf ( Math . abs ( num ) ) ; int sum = 0 ; for ( char c : w . toCharArray ( ) ) { sum += c - '0' ; } if ( num < 0 ) { sum -= 2 * ( w . charAt ( 0 ) - '0' ) ; } result . add ( sum ) ; } for ( int i = 0 ; i < nums . size ( ) ; i ++ ) { for ( int j = 1 ; j < nums . size ( ) ; j ++ ) { if ( result . get ( j - 1 ) > result . get ( j ) ) { Collections . swap ( result , j , j - 1 ) ; Collections . swap ( nums , j , j - 1 ) ; } } } return nums ; } 
List < String > bf ( String planet1 , String planet2 ) { List < String > planets = Arrays . asList ( "Mercury" , "Venus" , "Earth" , "Mars" , "Jupiter" , "Saturn" , "Uranus" , "Neptune" ) ; int idx1 = planets . indexOf ( planet1 ) ; int idx2 = planets . indexOf ( planet2 ) ; if ( idx1 == - 1 || idx2 == - 1 || idx1 == idx2 ) { return new ArrayList < > ( ) ; } return idx1 > idx2 ? planets . subList ( idx2 + 1 , idx1 ) : planets . subList ( idx1 + 1 , idx2 ) ; } 
List < String > sortedListSum ( List < String > lst ) { List < String > result = new ArrayList < > ( ) ; for ( var i : lst ) { if ( i . length ( ) % 2 == 0 ) { result . add ( i ) ; } } result . sort ( ( String l , String r ) -> { if ( l . length ( ) == r . length ( ) ) { return l . compareTo ( r ) ; } return l . length ( ) - r . length ( ) ; } ) ; return result ; } 
boolean cycpatternCheck ( String a , String b ) { for ( int i = 0 ; i <= b . length ( ) ; i ++ ) { String rotate = b . substring ( i ) + b . substring ( 0 , i ) ; if ( a . contains ( rotate ) ) { return true ; } } return false ; } 
List < Integer > evenOddCount ( int num ) { int evenCount = 0 , oddCount = 0 ; for ( char i : String . valueOf ( Math . abs ( num ) ) . toCharArray ( ) ) { if ( i % 2 == 0 ) { evenCount += 1 ; } else { oddCount += 1 ; } } return Arrays . asList ( evenCount , oddCount ) ; } 
String findMax ( List < String > words ) { String max = "" ; int maxLength = 0 ; for ( var word : words ) { List < Character > unique = new ArrayList < > ( ) ; for ( char w : word . toCharArray ( ) ) { if ( ! unique . contains ( w ) ) { unique . add ( w ) ; } } if ( unique . size ( ) > maxLength || ( unique . size ( ) == maxLength && word . compareTo ( max ) < 0 ) ) { max = word ; maxLength = unique . size ( ) ; } } return max ; } 
String solve ( String s ) { boolean noLetter = true ; StringBuilder result = new StringBuilder ( ) ; for ( char ch : s . toCharArray ( ) ) { if ( Character . isUpperCase ( ch ) ) { ch = Character . toLowerCase ( ch ) ; noLetter = false ; } else if ( Character . isLowerCase ( ch ) ) { ch = Character . toUpperCase ( ch ) ; noLetter = false ; } result . append ( ch ) ; } if ( noLetter ) { return result . reverse ( ) . toString ( ) ; } else { return result . toString ( ) ; } } 
int mostFrequent ( List < Integer > arr , int n ) { Map < Integer , Integer > hp = new HashMap < > ( ) ; for ( int i = 0 ; i < n ; i ++ ) { if ( hp . containsKey ( arr . get ( i ) ) ) { hp . put ( arr . get ( i ) , hp . get ( arr . get ( i ) ) + 1 ) ; } else { hp . put ( arr . get ( i ) , 1 ) ; } } int maxCount = 0 , res = - 1 ; for ( var entry : hp . entrySet ( ) ) { if ( maxCount < entry . getValue ( ) ) { res = entry . getKey ( ) ; maxCount = entry . getValue ( ) ; } } return res ; }
int find ( List < Integer > a , List < Integer > b , int k , int n1 , int n2 ) { Set < Integer > s = new HashSet < > ( ) ; for ( int i = 0 ; i < n2 ; i ++ ) { s . add ( b . get ( i ) ) ; } int missing = 0 ; for ( int i = 0 ; i < n1 ; i ++ ) { if ( ! s . contains ( a . get ( i ) ) ) { missing ++ ; } if ( missing == k ) { return a . get ( i ) ; } } return - 1 ; } 
int solveQuery ( int start , int end , List < Integer > arr ) { Map < Integer , Integer > mp = new HashMap < > ( ) ; for ( int i = start ; i <= end ; i ++ ) { mp . put ( arr . get ( i ) , mp . getOrDefault ( arr . get ( i ) , 0 ) + 1 ) ; } int count = 0 ; for ( var entry : mp . entrySet ( ) ) { if ( entry . getKey ( ) == entry . getValue ( ) ) { count ++ ; } } return count ; } 
int segregate ( List < Integer > arr , int size ) { int j = 0 ; for ( int i = 0 ; i < size ; i ++ ) { if ( arr . get ( i ) <= 0 ) { Collections . swap ( arr , i , j ) ; j ++ ; } } return j ; } 
int countTriplets ( List < Integer > a , int n ) { Set < Integer > s = new HashSet < > ( ) ; for ( int i = 0 ; i < n ; i ++ ) { s . add ( a . get ( i ) ) ; } int count = 0 ; for ( int i = 0 ; i < n ; i ++ ) { for ( int j = i + 1 ; j < n ; j ++ ) { int xr = a . get ( i ) ^ a . get ( j ) ; if ( s . contains ( xr ) && xr != a . get ( i ) && xr != a . get ( j ) ) { count ++ ; } } } return count / 3 ; } 
int leastFrequent ( List < Integer > arr , int n ) { Map < Integer , Integer > hp = new HashMap < > ( ) ; for ( int i = 0 ; i < n ; i ++ ) { if ( hp . containsKey ( arr . get ( i ) ) ) { hp . put ( arr . get ( i ) , hp . get ( arr . get ( i ) ) + 1 ) ; } else { hp . put ( arr . get ( i ) , 1 ) ; } } int minCount = n + 1 , res = - 1 ; for ( var entry : hp . entrySet ( ) ) { if ( minCount >= entry . getValue ( ) ) { res = entry . getKey ( ) ; minCount = entry . getValue ( ) ; } } return res ; } 
int findPermutations ( List < Integer > arr ) { int cnt = 0 ; int maxInd = - 1 , minInd = 10000000 ; int n = arr . size ( ) ; Map < Integer , Integer > indexOf = new HashMap < > ( ) ; for ( int i = 0 ; i < n ; i ++ ) { indexOf . put ( arr . get ( i ) , i + 1 ) ; } for ( int i = 1 ; i <= n ; i ++ ) { maxInd = Math . max ( maxInd , indexOf . getOrDefault ( i , 0 ) ) ; minInd = Math . min ( minInd , indexOf . getOrDefault ( i , 0 ) ) ; if ( maxInd - minInd + 1 == i ) { cnt ++ ; } } return cnt ; } 
int formQuadruplets ( List < Integer > arr , int n ) { int ans = 0 , pairs = 0 ; pairs = n / 4 ; arr . sort ( Collections . reverseOrder ( ) ) ; for ( int i = 0 ; i < n - pairs ; i += 3 ) { ans += arr . get ( i + 2 ) ; } return ans ; } 
String lexicographicallyMaximum ( String s , int n ) { Map < Character , Integer > m = new HashMap < > ( ) ; for ( int i = 0 ; i < n ; ++ i ) { if ( m . containsKey ( s . charAt ( i ) ) ) { m . put ( s . charAt ( i ) , m . get ( s . charAt ( i ) ) + 1 ) ; } else { m . put ( s . charAt ( i ) , 1 ) ; } } List < Character > v = new ArrayList < > ( ) ; for ( char i = 'a' ; i < 'a' + Math . min ( n , 25 ) ; ++ i ) { if ( ! m . containsKey ( i ) ) { v . add ( i ) ; } } int j = v . size ( ) - 1 ; for ( int i = 0 ; i < n ; ++ i ) { if ( s . charAt ( i ) >= 'a' + Math . min ( n , 25 ) || ( m . containsKey ( s . charAt ( i ) ) && m . get ( s . charAt ( i ) ) > 1 ) ) { if ( v . get ( j ) < s . charAt ( i ) ) { continue ; } m . put ( s . charAt ( i ) , m . get ( s . charAt ( i ) ) - 1 ) ; s = s . substring ( 0 , i ) + v . get ( j ) + s . substring ( i + 1 ) ; j -- ; } if ( j < 0 ) { break ; } } int l = 0 ; for ( int i = n - 1 ; i >= 0 ; i -- ) { if ( l > j ) { break ; } if ( s . charAt ( i ) >= 'a' + Math . min ( n , 25 ) || m . containsKey ( s . charAt ( i ) ) && m . get ( s . charAt ( i ) ) > 1 ) { m . put ( s . charAt ( i ) , m . get ( s . charAt ( i ) ) - 1 ) ; s = s . substring ( 0 , i ) + v . get ( l ) + s . substring ( i + 1 ) ; l ++ ; } } return s ; } 
int noOfValidKbers ( int k , List < Integer > arr ) { Set < Integer > s = new HashSet < > ( ) ; while ( k != 0 ) { s . add ( k % 10 ) ; k = k / 10 ; } int count = 0 ; for ( int i = 0 ; i < arr . size ( ) ; i ++ ) { int no = arr . get ( i ) ; boolean flag = true ; while ( no != 0 ) { int digit = no % 10 ; if ( ! s . contains ( digit ) ) { flag = false ; break ; } no = no / 10 ; } if ( flag ) { count ++ ; } } return count ; } 
int delCost ( String s , List < Integer > cost ) { int ans = 0 ; Map < Character , Integer > forMax = new HashMap < > ( ) ; Map < Character , Integer > forTot = new HashMap < > ( ) ; for ( int i = 0 ; i < s . length ( ) ; i ++ ) { if ( ! forMax . containsKey ( s . charAt ( i ) ) ) { forMax . put ( s . charAt ( i ) , cost . get ( i ) ) ; } else { forMax . put ( s . charAt ( i ) , Math . max ( cost . get ( i ) , forMax . get ( s . charAt ( i ) ) ) ) ; } if ( ! forTot . containsKey ( s . charAt ( i ) ) ) { forTot . put ( s . charAt ( i ) , cost . get ( i ) ) ; } else { forTot . put ( s . charAt ( i ) , forTot . get ( s . charAt ( i ) ) + cost . get ( i ) ) ; } } for ( var i : forMax . entrySet ( ) ) { ans += forTot . get ( i . getKey ( ) ) - i . getValue ( ) ; } return ans ; } 
List < String > replaceDuplicates ( List < String > names ) { Map < String , Integer > hash = new HashMap < > ( ) ; for ( int i = 0 ; i < names . size ( ) ; i ++ ) { if ( ! hash . containsKey ( names . get ( i ) ) ) { hash . put ( names . get ( i ) , 1 ) ; } else { int count = hash . get ( names . get ( i ) ) ; hash . put ( names . get ( i ) , hash . get ( names . get ( i ) ) + 1 ) ; names . set ( i , names . get ( i ) + Integer . toString ( count ) ) ; } } return names ; } 
List < Integer > minmaxNumbers ( List < List < Integer > > matrix , List < Integer > res ) { Set < Integer > set = new HashSet < > ( ) ; for ( int i = 0 ; i < matrix . size ( ) ; i ++ ) { int minR = Integer . MAX_VALUE ; for ( int j = 0 ; j < matrix . get ( i ) . size ( ) ; j ++ ) { minR = Math . min ( minR , matrix . get ( i ) . get ( j ) ) ; } set . add ( minR ) ; } for ( int j = 0 ; j < matrix . get ( 0 ) . size ( ) ; j ++ ) { int maxC = Integer . MIN_VALUE ; for ( int i = 0 ; i < matrix . size ( ) ; i ++ ) { maxC = Math . max ( maxC , matrix . get ( i ) . get ( j ) ) ; } if ( set . contains ( maxC ) ) { res . add ( maxC ) ; } } return res ; } 
int lengthOfLongestAP ( List < Integer > a , int n ) { Map < Integer , Map < Integer , Integer > > dp = new HashMap < Integer , Map < Integer , Integer > > ( ) ; int res = 2 ; for ( int i = 0 ; i < n ; ++ i ) { for ( int j = i + 1 ; j < n ; ++ j ) { int d = a . get ( j ) - a . get ( i ) ; if ( dp . containsKey ( d ) ) { if ( dp . get ( d ) . containsKey ( i ) ) { dp . get ( d ) . put ( j , dp . get ( d ) . get ( i ) + 1 ) ; } else { dp . get ( d ) . put ( j , 2 ) ; } } else { dp . put ( d , new HashMap < > ( ) ) ; dp . get ( d ) . put ( j , 2 ) ; } res = Math . max ( res , dp . get ( d ) . get ( j ) ) ; } } return res ; } 
char findKthChar ( int n , int k ) { String prev = "A" ; String cur = "" ; if ( n == 1 ) { return 'A' ; } for ( int j = 2 ; j <= n ; j ++ ) { cur = prev + "B" ; for ( int i = 0 ; i < prev . length ( ) ; i ++ ) { if ( prev . charAt ( i ) == 'A' ) { prev = prev . substring ( 0 , i ) + 'B' + prev . substring ( i + 1 ) ; } else { prev = prev . substring ( 0 , i ) + 'A' + prev . substring ( i + 1 ) ; } } prev = new StringBuilder ( prev ) . reverse ( ) . toString ( ) ; cur += prev ; prev = cur ; } return cur . charAt ( k - 1 ) ; } 
char findKthLargest ( String s , int k ) { List < Character > tmp = s . chars ( ) . mapToObj ( e -> ( char ) e ) . collect ( Collectors . toList ( ) ) ; Collections . sort ( tmp ) ; Collections . reverse ( tmp ) ; return tmp . get ( k - 1 ) ; }
int subArraylen ( List < Integer > arr , int n , int k ) { HashMap < Integer , Integer > mp = new HashMap < > ( ) ; mp . put ( arr . get ( 0 ) , 0 ) ; for ( int i = 1 ; i < n ; i ++ ) { arr . set ( i , arr . get ( i ) + arr . get ( i - 1 ) ) ; mp . put ( arr . get ( i ) , i ) ; } int len = Integer . MAX_VALUE ; for ( int i = 0 ; i < n ; i ++ ) { if ( arr . get ( i ) < k ) { continue ; } else { int x = arr . get ( i ) - k ; if ( x == 0 ) { len = Math . min ( len , i ) ; } if ( ! mp . containsKey ( x ) ) { continue ; } else { len = Math . min ( len , i - mp . get ( x ) ) ; } } } return len ; } 
int findMaxLen ( List < Integer > a , int k ) { int n = a . size ( ) ; Collections . sort ( a ) ; List < Boolean > vis = new ArrayList < > ( Collections . nCopies ( n , false ) ) ; HashMap < Integer , Integer > mp = new HashMap < > ( ) ; for ( int i = 0 ; i < n ; i ++ ) { mp . put ( a . get ( i ) , i ) ; } int c = 0 ; for ( int i = 0 ; i < n ; ++ i ) { if ( ! vis . get ( i ) ) { int check = a . get ( i ) * k ; if ( mp . containsKey ( check ) ) { c ++ ; vis . set ( mp . get ( check ) , true ) ; } } } return n - c ; } 
List < Integer > minDistancePoints ( List < Integer > a , int k , int n ) { Map < Integer , Integer > m = new HashMap < > ( ) ; Queue < Integer > q = new ArrayDeque < > ( ) ; for ( int i = 0 ; i < n ; ++ i ) { m . put ( a . get ( i ) , 1 ) ; q . add ( a . get ( i ) ) ; } List < Integer > ans = new ArrayList < > ( ) ; while ( k > 0 ) { int x = q . poll ( ) ; if ( ! m . containsKey ( x - 1 ) && k > 0 ) { m . put ( x - 1 , 1 ) ; q . add ( x - 1 ) ; ans . add ( x - 1 ) ; k -- ; } if ( ! m . containsKey ( x + 1 ) && k > 0 ) { m . put ( x + 1 , 1 ) ; q . add ( x + 1 ) ; ans . add ( x + 1 ) ; k -- ; } } return ans ; } 
boolean isValidLen ( String s , int len , int k ) { int n = s . length ( ) ; Map < Character , Integer > mp = new HashMap < Character , Integer > ( ) ; int right = 0 ; while ( right < len ) { if ( mp . containsKey ( s . charAt ( right ) ) ) { mp . put ( s . charAt ( right ) , mp . get ( s . charAt ( right ) ) + 1 ) ; } else { mp . put ( s . charAt ( right ) , 1 ) ; } right ++ ; } if ( mp . size ( ) <= k ) { return true ; } while ( right < n ) { if ( mp . containsKey ( s . charAt ( right ) ) ) { mp . put ( s . charAt ( right ) , mp . get ( s . charAt ( right ) ) + 1 ) ; } else { mp . put ( s . charAt ( right ) , 1 ) ; } if ( mp . containsKey ( s . charAt ( right - len ) ) ) { mp . put ( s . charAt ( right - len ) , mp . get ( s . charAt ( right - len ) ) - 1 ) ; } if ( mp . get ( s . charAt ( right - len ) ) == 0 ) { mp . remove ( s . charAt ( right - len ) ) ; } if ( mp . size ( ) <= k ) { return true ; } right ++ ; } return mp . size ( ) <= k ; } 
int partition ( List < Integer > arr , int low , int high ) { int pivot = arr . get ( high ) ; int i = ( low - 1 ) ; for ( int j = low ; j <= high - 1 ; j ++ ) { if ( arr . get ( j ) <= pivot ) { i ++ ; Collections . swap ( arr , i , j ) ; } } Collections . swap ( arr , i + 1 , high ) ; return i + 1 ; } 
int strScore ( List < String > strs , String s , int n ) { HashMap < String , Integer > m = new HashMap < > ( ) ; for ( int i = 0 ; i < n ; i ++ ) { m . put ( strs . get ( i ) , i + 1 ) ; } if ( ! m . containsKey ( s ) ) { return 0 ; } int score = 0 ; for ( int i = 0 ; i < s . length ( ) ; i ++ ) { score += s . charAt ( i ) - 'a' + 1 ; } score = score * m . get ( s ) ; return score ; } 
List < Integer > countEle ( List < Integer > s , List < Integer > a , int n ) { HashMap < Integer , Boolean > mp = new HashMap < > ( ) ; List < Integer > ans = new ArrayList < > ( ) ; for ( int i = 0 ; i < n ; ++ i ) { int num = a . get ( i ) ; if ( mp . containsKey ( num ) ) { ans . add ( 0 ) ; } else { int cnt = 0 ; while ( s . get ( 0 ) != num ) { mp . put ( s . get ( 0 ) , true ) ; s . remove ( 0 ) ; cnt ++ ; } s . remove ( 0 ) ; cnt ++ ; ans . add ( cnt ) ; } } return ans ; } 
int maxDistinctChar ( String s , int n , int k ) { Map < Character , Integer > freq = new HashMap < > ( ) ; for ( int i = 0 ; i < n ; i ++ ) { if ( freq . containsKey ( s . charAt ( i ) ) ) { freq . put ( s . charAt ( i ) , freq . get ( s . charAt ( i ) ) + 1 ) ; } else { freq . put ( s . charAt ( i ) , 1 ) ; } } List < Integer > v = new ArrayList < > ( ) ; for ( var it : freq . entrySet ( ) ) { v . add ( it . getValue ( ) ) ; } Collections . sort ( v ) ; for ( int i = 0 ; i < v . size ( ) ; i ++ ) { int mn = Math . min ( v . get ( i ) - 1 , k ) ; v . set ( i , v . get ( i ) - mn ) ; k -= mn ; } if ( k > 0 ) { for ( int i = 0 ; i < v . size ( ) ; i ++ ) { int mn = Math . min ( v . get ( i ) , k ) ; v . set ( i , v . get ( i ) - mn ) ; k -= mn ; } } int res = 0 ; for ( int i = 0 ; i < v . size ( ) ; i ++ ) { if ( v . get ( i ) == 1 ) { res ++ ; } } return res ; } 
int findKth ( List < Integer > arr , int n , int k ) { HashSet < Integer > missing = new HashSet < > ( ) ; int count = 0 ; for ( int i = 0 ; i < n ; i ++ ) { missing . add ( arr . get ( i ) ) ; } int maxM = Collections . max ( arr ) ; int minM = Collections . min ( arr ) ; for ( int i = minM + 1 ; i < maxM ; i ++ ) { if ( ! missing . contains ( i ) ) { count ++ ; } if ( count == k ) { return i ; } } return - 1 ; } 
boolean almostSort ( List < Integer > a , int n ) { for ( int i = 0 ; i < n - 1 ; i ++ ) { if ( a . get ( i ) > a . get ( i + 1 ) ) { Collections . swap ( a , i , i + 1 ) ; i ++ ; } } for ( int i = 0 ; i < n - 1 ; i ++ ) { if ( a . get ( i ) > a . get ( i + 1 ) ) { return false ; } } return true ; } 
int maximumSum ( String s , int n , int k ) { int sum = 0 ; List < Integer > freq = new ArrayList < > ( Collections . nCopies ( 256 , 0 ) ) ; for ( int i = 0 ; i < n ; i ++ ) { freq . set ( s . charAt ( i ) , freq . get ( s . charAt ( i ) ) + 1 ) ; } freq . sort ( Collections . reverseOrder ( ) ) ; for ( int i = 0 ; i < 256 ; i ++ ) { if ( k > freq . get ( i ) ) { sum += freq . get ( i ) * freq . get ( i ) ; k -= freq . get ( i ) ; } else { sum += freq . get ( i ) * k ; break ; } } return sum ; } 
int findMinOperations ( List < Integer > arr , int N , int K ) { int operations = 0 ; for ( int i = 0 ; i < K ; i ++ ) { Map < Integer , Integer > freq = new HashMap < > ( ) ; for ( int j = i ; j < N ; j += K ) { freq . put ( arr . get ( j ) , freq . getOrDefault ( arr . get ( j ) , 0 ) + 1 ) ; } int max1 = 0 , num = 0 ; for ( var entry : freq . entrySet ( ) ) { if ( entry . getValue ( ) > max1 ) { max1 = entry . getValue ( ) ; num = entry . getKey ( ) ; } } for ( var entry : freq . entrySet ( ) ) { if ( entry . getKey ( ) != num ) { operations += entry . getValue ( ) ; } } } return operations ; } 
List < String > subString ( String s , int n ) { List < String > v = new ArrayList < > ( ) ; for ( int i = 0 ; i < n ; i ++ ) { for ( int len = 1 ; len <= n - i ; len ++ ) { String find = s . substring ( i , i + len ) ; v . add ( find ) ; } } return v ; } 
boolean checkUniqueFrequency ( List < Integer > arr , int n ) { Map < Integer , Integer > freq = new HashMap < > ( ) ; for ( int i = 0 ; i < n ; i ++ ) { freq . put ( arr . get ( i ) , freq . getOrDefault ( arr . get ( i ) , 0 ) + 1 ) ; } Set < Integer > uniqueFreq = new HashSet < > ( ) ; for ( var entry : freq . entrySet ( ) ) { if ( uniqueFreq . contains ( entry . getValue ( ) ) ) { return false ; } else { uniqueFreq . add ( entry . getValue ( ) ) ; } } return true ; } 
int minCost ( String str1 , String str2 , int n ) { int cost = 0 ; char [ ] tmp = str1 . toCharArray ( ) ; for ( int i = 0 ; i < n ; i ++ ) { if ( tmp [ i ] != str2 . charAt ( i ) ) { if ( i < n - 1 && tmp [ i + 1 ] != str2 . charAt ( i + 1 ) ) { char c = tmp [ i ] ; tmp [ i ] = tmp [ i + 1 ] ; tmp [ i + 1 ] = c ; cost ++ ; } else { cost ++ ; } } } return cost ; } 
boolean isValidNum ( String x ) { Map < Integer , Integer > mp = new HashMap < > ( ) ; for ( int i = 0 ; i < x . length ( ) ; i ++ ) { if ( mp . containsKey ( x . charAt ( i ) - '0' ) ) { return false ; } else if ( x . charAt ( i ) - '0' > 5 ) { return false ; } else { mp . put ( x . charAt ( i ) - '0' , 1 ) ; } } return true ; } 
int minimizeDiff ( List < Integer > arr , int n , int k ) { int max = Collections . max ( arr ) ; int min = Collections . min ( arr ) ; if ( max - min <= k ) { return max - min ; } int avg = ( max + min ) / 2 ; for ( int i = 0 ; i < n ; i ++ ) { if ( arr . get ( i ) > avg ) { arr . set ( i , arr . get ( i ) - k ) ; } else { arr . set ( i , arr . get ( i ) + k ) ; } } max = Collections . max ( arr ) ; min = Collections . min ( arr ) ; return max - min ; }
int getMinCost ( List < Integer > arr , int n ) { int minEle = Collections . min ( arr ) ; return minEle * ( n - 1 ) ; } 
boolean possibility ( Map < Integer , Integer > m , int length , String s ) { int countOdd = 0 ; for ( int i = 0 ; i < length ; i ++ ) { if ( ( m . get ( s . charAt ( i ) - '0' ) & 1 ) != 0 ) { countOdd ++ ; } if ( countOdd > 1 ) { return false ; } } return true ; } 
int minimumCostOfBreaking ( List < Integer > x , List < Integer > y , int m , int n ) { int res = 0 ; x . sort ( Collections . reverseOrder ( ) ) ; y . sort ( Collections . reverseOrder ( ) ) ; int hzntl = 1 , vert = 1 ; int i = 0 , j = 0 ; while ( i < m && j < n ) { if ( x . get ( i ) > y . get ( j ) ) { res += x . get ( i ) * vert ; hzntl ++ ; i ++ ; } else { res += y . get ( j ) * hzntl ; vert ++ ; j ++ ; } } int total = 0 ; while ( i < m ) { total += x . get ( i ++ ) ; } res += total * vert ; total = 0 ; while ( j < n ) { total += y . get ( j ++ ) ; } res += total * hzntl ; return res ; } 
int findMaximumScore ( List < Integer > a , int n ) { Map < Integer , Integer > freq = new HashMap < > ( ) ; for ( int i = 0 ; i < n ; i ++ ) { if ( freq . containsKey ( a . get ( i ) ) ) { freq . put ( a . get ( i ) , freq . get ( a . get ( i ) ) + 1 ) ; } else { freq . put ( a . get ( i ) , 1 ) ; } } int [ ] dp = new int [ Collections . max ( a ) + 1 ] ; dp [ 0 ] = 0 ; dp [ 1 ] = freq . getOrDefault ( 1 , 0 ) ; for ( int i = 2 ; i < dp . length ; i ++ ) { dp [ i ] = Math . max ( dp [ i - 1 ] , dp [ i - 2 ] + freq . getOrDefault ( i , 0 ) * i ) ; } return dp [ dp . length - 1 ] ; } 
int countWays ( String s , String t , int k , int mod ) { int n = s . length ( ) ; int a = 0 , b = 0 ; for ( int i = 0 ; i < n ; i ++ ) { String p = s . substring ( i , n ) + s . substring ( 0 , i ) ; if ( p . equals ( t ) ) { a ++ ; } else { b ++ ; } } int [ ] dp1 = new int [ k + 1 ] ; int [ ] dp2 = new int [ k + 1 ] ; if ( s . equals ( t ) ) { dp1 [ 0 ] = 1 ; dp2 [ 0 ] = 0 ; } else { dp1 [ 0 ] = 0 ; dp2 [ 0 ] = 1 ; } for ( int i = 1 ; i <= k ; i ++ ) { dp1 [ i ] = ( ( dp1 [ i - 1 ] * ( a - 1 ) ) % mod + ( dp2 [ i - 1 ] * a ) % mod ) % mod ; dp2 [ i ] = ( ( dp1 [ i - 1 ] * ( b ) ) % mod + ( dp2 [ i - 1 ] * ( b - 1 ) ) % mod ) % mod ; } return dp1 [ k ] ; } 
int findSubarraySum ( List < Integer > arr , int n , int k ) { Map < Integer , Integer > prevSum = new HashMap < > ( ) ; int res = 0 ; int currSum = 0 ; for ( int i = 0 ; i < n ; i ++ ) { currSum += arr . get ( i ) ; if ( currSum == k ) { res ++ ; } if ( prevSum . containsKey ( currSum - k ) ) { res += prevSum . get ( currSum - k ) ; } prevSum . put ( currSum , prevSum . getOrDefault ( currSum , 0 ) + 1 ) ; } return res ; } 
int maximumOccurrence ( String s ) { int n = s . length ( ) ; Map < String , Integer > freq = new HashMap < > ( ) ; int i , j ; for ( i = 0 ; i < n ; i ++ ) { String temp = "" ; temp += s . charAt ( i ) ; freq . put ( temp , freq . getOrDefault ( temp , 0 ) + 1 ) ; } for ( i = 0 ; i < n ; i ++ ) { for ( j = i + 1 ; j < n ; j ++ ) { String temp = "" ; temp += s . charAt ( i ) ; temp += s . charAt ( j ) ; freq . put ( temp , freq . getOrDefault ( temp , 0 ) + 1 ) ; } } int answer = Integer . MIN_VALUE ; for ( var entry : freq . entrySet ( ) ) { answer = Math . max ( answer , entry . getValue ( ) ) ; } return answer ; } 
int countCharacters ( List < String > strings , String chars ) { int res = 0 ; Map < Character , Integer > freq = new HashMap < > ( ) ; for ( int i = 0 ; i < chars . length ( ) ; i ++ ) { freq . put ( chars . charAt ( i ) , freq . getOrDefault ( chars . charAt ( i ) , 0 ) + 1 ) ; } for ( String st : strings ) { boolean flag = true ; for ( char c : st . toCharArray ( ) ) { if ( ! freq . containsKey ( c ) ) { flag = false ; break ; } } if ( flag ) { res += st . length ( ) ; } } return res ; } 
int distinctSubstring ( String p , String q , int k , int n ) { Set < String > ss = new HashSet < > ( ) ; for ( int i = 0 ; i < n ; ++ i ) { int sum = 0 ; String s = "" ; for ( int j = i ; j < n ; ++ j ) { int pos = p . charAt ( j ) - 'a' ; sum += q . charAt ( pos ) - '0' ; s += p . charAt ( j ) ; if ( sum <= k ) { ss . add ( s ) ; } else { break ; } } } return ss . size ( ) ; } 
int uniqueMorseRep ( List < String > arr ) { List < String > morseCode = Arrays . asList ( ".-" , "-..." , "-.-." , "-.." , "." , "..-." , "--." , "...." , ".." , ".---" , "-.-" , ".-.." , "--" , "-." , "---" , ".--." , "--.-" , ".-." , "..." , "-" , "..-" , "...-" , ".--" , "-..-" , "-.--" , "--.." ) ; Set < String > st = new HashSet < > ( ) ; int n = arr . size ( ) ; for ( int i = 0 ; i < n ; i ++ ) { String temp = "" ; int m = arr . get ( i ) . length ( ) ; for ( int j = 0 ; j < m ; j ++ ) { temp += morseCode . get ( arr . get ( i ) . charAt ( j ) - 'a' ) ; } st . add ( temp ) ; } return st . size ( ) ; } 
int countSubstrings ( String st , int k ) { int n = st . length ( ) ; int answer = 0 ; Map < Character , Integer > map = new HashMap < > ( ) ; for ( int i = 0 ; i < k ; i ++ ) { if ( ! map . containsKey ( st . charAt ( i ) ) ) { map . put ( st . charAt ( i ) , 1 ) ; } else { map . put ( st . charAt ( i ) , map . get ( st . charAt ( i ) ) + 1 ) ; } } if ( map . size ( ) == k ) { answer ++ ; } for ( int i = k ; i < n ; i ++ ) { if ( ! map . containsKey ( st . charAt ( i ) ) ) { map . put ( st . charAt ( i ) , 1 ) ; } else { map . put ( st . charAt ( i ) , map . get ( st . charAt ( i ) ) + 1 ) ; } map . put ( st . charAt ( i - k ) , map . get ( st . charAt ( i - k ) ) - 1 ) ; if ( map . get ( st . charAt ( i - k ) ) == 0 ) { map . remove ( st . charAt ( i - k ) ) ; } if ( map . size ( ) == k ) { answer ++ ; } } return answer ; } 
boolean canConstruct ( String s , int k ) { Map < Character , Integer > m = new HashMap < > ( ) ; int p = 0 ; if ( s . length ( ) == k ) { return true ; } for ( int i = 0 ; i < s . length ( ) ; i ++ ) { m . put ( s . charAt ( i ) , m . getOrDefault ( s . charAt ( i ) , 0 ) + 1 ) ; } if ( k > s . length ( ) ) { return false ; } else { for ( var h : m . entrySet ( ) ) { if ( h . getValue ( ) % 2 != 0 ) { p = p + 1 ; } } } if ( k < p ) { return false ; } return true ; } 
boolean equalIgnoreCase ( String str1 , String str2 ) { str1 = str1 . toUpperCase ( ) ; str2 = str2 . toUpperCase ( ) ; return str1 . equals ( str2 ) ; } 
int findLongestSub ( String bin ) { int n = bin . length ( ) , i ; int sum = 0 ; HashMap < Integer , Integer > prevSum = new HashMap < > ( ) ; int maxLen = 0 ; for ( i = 0 ; i < n ; i ++ ) { if ( bin . charAt ( i ) == '1' ) { sum ++ ; } else { sum -- ; } if ( sum > 0 ) { maxLen = i + 1 ; } else if ( sum <= 0 ) { if ( prevSum . containsKey ( sum - 1 ) ) { int currLen = i - prevSum . get ( sum - 1 ) ; maxLen = Math . max ( maxLen , currLen ) ; } } if ( ! prevSum . containsKey ( sum ) ) { prevSum . put ( sum , i ) ; } } return maxLen ; } 
boolean hasAllCodes ( String s , int k ) { Set < String > us = new HashSet < > ( ) ; for ( int i = 0 ; i + k <= s . length ( ) ; i ++ ) { us . add ( s . substring ( i , i + k ) ) ; } return us . size ( ) == 1 << k ; } 
boolean checkPalin ( String word ) { int n = word . length ( ) ; word = word . toLowerCase ( ) ; for ( int i = 0 ; i < n ; i ++ , n -- ) { if ( word . charAt ( i ) != word . charAt ( n - 1 ) ) { return false ; } } return true ; } 
String convert ( String st ) { String w = "" , z = "" ; st = st . toUpperCase ( ) + " " ; for ( int i = 0 ; i < st . length ( ) ; i ++ ) { char ch = st . charAt ( i ) ; if ( ch != ' ' ) { w += ch ; } else { z += Character . toLowerCase ( w . charAt ( 0 ) ) + w . substring ( 1 ) + " " ; w = "" ; } } return z ; } 
int maxLines ( int n , List < Integer > x1 , List < Integer > y1 , List < Integer > x2 , List < Integer > y2 ) { Set < Double > s = new HashSet < > ( ) ; double slope ; for ( int i = 0 ; i < n ; ++ i ) { if ( x1 . get ( i ) == x2 . get ( i ) ) { slope = Integer . MAX_VALUE ; } else { slope = ( y2 . get ( i ) - y1 . get ( i ) ) * 1.0 / ( x2 . get ( i ) - x1 . get ( i ) ) ; } s . add ( slope ) ; } return s . size ( ) ; } 
HashMap < Integer , Integer > PrimeFactor ( int n ) { HashMap < Integer , Integer > primef = new HashMap < > ( ) ; while ( n % 2 == 0 ) { if ( primef . containsKey ( 2 ) ) { primef . put ( 2 , primef . get ( 2 ) + 1 ) ; } else { primef . put ( 2 , 1 ) ; } n /= 2 ; } for ( int i = 3 ; i <= Math . sqrt ( n ) ; i ++ ) { while ( n % i == 0 ) { if ( primef . containsKey ( i ) ) { primef . put ( i , primef . get ( i ) + 1 ) ; } else { primef . put ( i , 1 ) ; } n /= i ; } } if ( n > 2 ) { primef . put ( n , 1 ) ; } return primef ; } 
String isDivisibleByDivisor ( int s , int d ) { s %= d ; Set < Integer > hashMap = new HashSet < > ( ) ; hashMap . add ( s ) ; for ( int i = 0 ; i <= d ; i ++ ) { s += s % d ; s %= d ; if ( hashMap . contains ( s ) ) { if ( s == 0 ) { return "Yes" ; } return "No" ; } else { hashMap . add ( s ) ; } } return "Yes" ; } 
boolean oddSum ( List < Integer > a , int n , int k ) { Set < Integer > odd = new HashSet < > ( ) ; Set < Integer > even = new HashSet < > ( ) ; for ( int i = 0 ; i < n ; i ++ ) { if ( a . get ( i ) % 2 == 0 ) { even . add ( a . get ( i ) ) ; } else { odd . add ( a . get ( i ) ) ; } } if ( odd . size ( ) >= k ) { return true ; } boolean flag = false ; for ( int i = 1 ; i < k ; i += 2 ) { int needed = k - i ; if ( needed <= even . size ( ) ) { return true ; } } return flag ; } 
int dayOfYear ( String date ) { List < Integer > days = Arrays . asList ( 31 , 28 , 31 , 30 , 31 , 30 , 31 , 31 , 30 , 31 , 30 , 31 ) ; int year = Integer . parseInt ( date . substring ( 0 , 4 ) ) ; int month = Integer . parseInt ( date . substring ( 5 , 7 ) ) ; int day = Integer . parseInt ( date . substring ( 8 ) ) ; if ( month > 2 && year % 4 == 0 && ( year % 100 != 0 || year % 400 == 0 ) ) { ++ day ; } while ( month > 1 ) { day = day + days . get ( month - 2 ) ; -- month ; } return day ; } 
boolean isPerfectSquare ( List < Integer > arr , int n ) { HashMap < Integer , Integer > umap = new HashMap < > ( ) ; for ( int i = 0 ; i < n ; i ++ ) { umap . put ( arr . get ( i ) , umap . getOrDefault ( arr . get ( i ) , 0 ) + 1 ) ; } for ( var itr : umap . entrySet ( ) ) { if ( itr . getValue ( ) % 2 == 1 ) { return false ; } } return true ; } 
int minMoves ( int n ) { String s = Integer . toString ( n ) ; int ans = Integer . MAX_VALUE ; int length = s . length ( ) ; for ( int i = 0 ; i < length ; ++ i ) { for ( int j = 0 ; j < length ; ++ j ) { if ( i == j ) { continue ; } char [ ] t = s . toCharArray ( ) ; int cur = 0 ; for ( int k = i ; k < length - 1 ; ++ k ) { char c = t [ k ] ; t [ k ] = t [ k + 1 ] ; t [ k + 1 ] = c ; ++ cur ; } for ( int k = j - ( j > i ? 1 : 0 ) ; k < length - 2 ; ++ k ) { char c = t [ k ] ; t [ k ] = t [ k + 1 ] ; t [ k + 1 ] = c ; ++ cur ; } int pos = - 1 ; for ( int k = 0 ; k < length ; ++ k ) { if ( t [ k ] != '0' ) { pos = k ; break ; } } for ( int k = pos ; k > 0 ; -- k ) { char c = t [ k ] ; t [ k ] = t [ k - 1 ] ; t [ k - 1 ] = c ; ++ cur ; } int nn = Integer . parseInt ( String . valueOf ( t ) ) ; if ( nn % 25 == 0 ) { ans = Math . min ( ans , cur ) ; } } } if ( ans == Integer . MAX_VALUE ) { return - 1 ; } return ans ; } 
int minimumOperations ( List < Integer > a , int n ) { HashMap < Integer , Integer > mp = new HashMap < > ( ) ; for ( int i = 0 ; i < n ; i ++ ) { mp . put ( a . get ( i ) , mp . getOrDefault ( a . get ( i ) , 0 ) + 1 ) ; } int count = 0 ; for ( var entry : mp . entrySet ( ) ) { if ( entry . getValue ( ) > 1 ) { count += entry . getValue ( ) - 1 ; } } return count ; } 
int kaprekarRec ( int n , int prev ) { if ( n == 0 ) { return 0 ; } prev = n ; int [ ] digits = new int [ 4 ] ; for ( int i = 0 ; i < 4 ; i ++ ) { digits [ i ] = n % 10 ; n = n / 10 ; } Arrays . sort ( digits ) ; int asc = 0 ; for ( int i = 0 ; i < 4 ; i ++ ) { asc = asc * 10 + digits [ i ] ; } Arrays . sort ( digits ) ; int desc = 0 ; for ( int i = 3 ; i >= 0 ; i -- ) { desc = desc * 10 + digits [ i ] ; } int diff = Math . abs ( asc - desc ) ; if ( diff == prev ) { return diff ; } return kaprekarRec ( diff , prev ) ; } 
String fractionToDecimal ( int numr , int denr ) { String res = "" ; HashMap < Integer , Integer > mp = new HashMap < > ( ) ; int rem = numr % denr ; while ( rem != 0 && ! mp . containsKey ( rem ) ) { mp . put ( rem , res . length ( ) ) ; rem = rem * 10 ; int resPart = rem / denr ; res += String . valueOf ( resPart ) ; rem = rem % denr ; } if ( rem == 0 ) { return "" ; } if ( mp . containsKey ( rem ) ) { return res . substring ( mp . get ( rem ) ) ; } return "" ; } 
boolean isFancy ( String num ) { Map < Character , Character > fp = new HashMap < Character , Character > ( ) ; fp . put ( '0' , '0' ) ; fp . put ( '1' , '1' ) ; fp . put ( '6' , '9' ) ; fp . put ( '8' , '8' ) ; fp . put ( '9' , '6' ) ; int n = num . length ( ) ; int l = 0 , r = n - 1 ; while ( l <= r ) { if ( ! fp . containsKey ( num . charAt ( l ) ) || fp . get ( num . charAt ( l ) ) != num . charAt ( r ) ) { return false ; } l ++ ; r -- ; } return true ; } 
