boolean hasCloseElements ( List < Double > numbers , double threshold ) { for ( int i = 0 ; i < numbers . size ( ) ; i ++ ) { for ( int j = i + 1 ; j < numbers . size ( ) ; j ++ ) { double distance = Math . abs ( numbers . get ( i ) - numbers . get ( j ) ) ; if ( distance < threshold ) return true ; } } return false ; }
double truncateNumber ( double number ) { return number % 1.0 ; } 
boolean belowZero ( List < Integer > operations ) { int balance = 0 ; for ( var op : operations ) { balance += op ; if ( balance < 0 ) { return true ; } } return false ; } 
double meanAbsoluteDeviation ( List < Double > numbers ) { double sumNum = 0 ; for ( var num : numbers ) { sumNum += num ; } double mean = sumNum / numbers . size ( ) ; double sumAbsDiff = 0 ; for ( var num : numbers ) { sumAbsDiff += Math . abs ( num - mean ) ; } return sumAbsDiff / numbers . size ( ) ; } 
List < Integer > intersperse ( List < Integer > numbers , int delimiter ) { List < Integer > result = new ArrayList < > ( ) ; if ( numbers . isEmpty ( ) ) { return result ; } for ( int i = 0 ; i < numbers . size ( ) - 1 ; i ++ ) { result . add ( numbers . get ( i ) ) ; result . add ( delimiter ) ; } result . add ( numbers . get ( numbers . size ( ) - 1 ) ) ; return result ; } 
List < Integer > sumProduct ( List < Integer > numbers ) { int sumValue = 0 ; int prodValue = 1 ; for ( Integer n : numbers ) { sumValue += n ; prodValue *= n ; } return Arrays . asList ( sumValue , prodValue ) ; } 
List < String > allPrefixes ( String s ) { List < String > result = new ArrayList < > ( ) ; for ( int i = 1 ; i <= s . length ( ) ; i ++ ) { result . add ( s . substring ( 0 , i ) ) ; } return result ; } 
List < Integer > parseMusic ( String musicString ) { StringBuilder current = new StringBuilder ( ) ; List < Integer > result = new ArrayList < > ( ) ; for ( int i = 0 ; i <= musicString . length ( ) ; i ++ ) { if ( i == musicString . length ( ) || musicString . charAt ( i ) == ' ' ) { if ( current . toString ( ) . equals ( "o" ) ) { result . add ( 4 ) ; } if ( current . toString ( ) . equals ( "o|" ) ) { result . add ( 2 ) ; } if ( current . toString ( ) . equals ( ".|" ) ) { result . add ( 1 ) ; } current . setLength ( 0 ) ; } else { current . append ( musicString . charAt ( i ) ) ; } } return result ; } 
int strlen ( String s ) { return s . length ( ) ; } 
List < Integer > factorize ( int n ) { List < Integer > factors = new ArrayList < > ( ) ; for ( int i = 2 ; i <= n ; i ++ ) { if ( n % i == 0 ) { n /= i ; factors . add ( i ) ; i -- ; } } return factors ; } 
String concatenate ( List < String > strings ) { StringBuilder result = new StringBuilder ( ) ; for ( var s : strings ) { result . append ( s ) ; } return result . toString ( ) ; } 
List < Double > getPositive ( List < Double > l ) { List < Double > result = new ArrayList < > ( ) ; for ( int i = 0 ; i < l . size ( ) ; i ++ ) { if ( l . get ( i ) > 0 ) { result . add ( l . get ( i ) ) ; } } return result ; } 
List < Double > sortEven ( List < Double > l ) { List < Double > evens = new ArrayList < > ( ) ; for ( int i = 0 ; i < l . size ( ) ; i += 2 ) { evens . add ( l . get ( i ) ) ; } Collections . sort ( evens ) ; List < Double > result = new ArrayList < > ( ) ; for ( int i = 0 ; i < l . size ( ) ; i ++ ) { if ( i % 2 == 0 ) { result . add ( evens . get ( i / 2 ) ) ; } if ( i % 2 == 1 ) { result . add ( l . get ( i ) ) ; } } return result ; } 
String decodeCyclic ( String s ) { StringBuilder output = new StringBuilder ( ) ; int i = 0 ; while ( i <= s . length ( ) - 3 ) { String x = s . charAt ( i + 2 ) + s . substring ( i , i + 2 ) ; output . append ( x ) ; i += 3 ; } return output . toString ( ) + s . substring ( i ) ; } 
int carRaceCollision ( int n ) { return ( int ) Math . pow ( n , 2 ) ; } 
List < Integer > incrList ( List < Integer > l ) { List < Integer > result = new ArrayList < > ( ) ; for ( int i : l ) { result . add ( i + 1 ) ; } return result ; } 
boolean pairsSumToZero ( List < Integer > l ) { for ( int i = 0 ; i < l . size ( ) ; i ++ ) { for ( int j = i + 1 ; j < l . size ( ) ; j ++ ) { if ( l . get ( i ) + l . get ( j ) == 0 ) { return true ; } } } return false ; } 
String changeBase ( int x , int b ) { StringBuilder ret = new StringBuilder ( ) ; while ( x > 0 ) { ret . insert ( 0 , x % b ) ; x /= b ; } return ret . toString ( ) ; } 
double median ( List < Double > l ) { Collections . sort ( l ) ; if ( l . size ( ) % 2 == 1 ) { return l . get ( l . size ( ) / 2 ) ; } return ( l . get ( l . size ( ) / 2 - 1 ) + l . get ( l . size ( ) / 2 ) ) / 2.0 ; } 
String decodeShift ( String s ) { StringBuilder sb = new StringBuilder ( ) ; for ( char ch : s . toCharArray ( ) ) { char w = ( char ) ( ( ch + 21 - 'a' ) % 26 + 'a' ) ; sb . append ( w ) ; } return sb . toString ( ) ; } 
boolean belowThreshold ( List < Integer > l , int t ) { for ( int n : l ) { if ( n >= t ) { return false ; } } return true ; } 
boolean correctBracketing ( String brackets ) { int depth = 0 ; for ( char b : brackets . toCharArray ( ) ) { if ( b == '<' ) { depth += 1 ; } if ( b == '>' ) { depth -= 1 ; } if ( depth < 0 ) { return false ; } } return depth == 0 ; } 
boolean monotonic ( List < Double > l ) { int incr = 0 ; int decr = 0 ; for ( int i = 1 ; i < l . size ( ) ; i ++ ) { if ( l . get ( i ) > l . get ( i - 1 ) ) { incr = 1 ; } if ( l . get ( i ) < l . get ( i - 1 ) ) { decr = 1 ; } } return incr + decr != 2 ; } 
List < Double > derivative ( List < Double > xs ) { List < Double > result = new ArrayList < > ( ) ; for ( int i = 1 ; i < xs . size ( ) ; i ++ ) { result . add ( i * xs . get ( i ) ) ; } return result ; } 
int vowelsCount ( String s ) { String vowels = "aeiouAEIOU" ; int count = 0 ; for ( char ch : s . toCharArray ( ) ) { if ( vowels . indexOf ( ch ) != - 1 ) { count += 1 ; } } if ( s . charAt ( s . length ( ) - 1 ) == 'y' || s . charAt ( s . length ( ) - 1 ) == 'Y' ) { count += 1 ; } return count ; } 
int digitSum ( String s ) { int sum = 0 ; for ( char c : s . toCharArray ( ) ) { if ( Character . isUpperCase ( c ) ) { sum += c ; } } return sum ; } 
int fruitDistribution ( String s , int n ) { StringBuilder num1 = new StringBuilder ( ) ; StringBuilder num2 = new StringBuilder ( ) ; boolean flag = false ; for ( int i = 0 ; i < s . length ( ) ; i ++ ) { if ( Character . isDigit ( s . charAt ( i ) ) ) { if ( ! flag ) { num1 . append ( s . charAt ( i ) ) ; } if ( flag ) { num2 . append ( s . charAt ( i ) ) ; } } else if ( ! flag && num1 . length ( ) > 0 ) { flag = true ; } } return n - Integer . parseInt ( num1 . toString ( ) ) - Integer . parseInt ( num2 . toString ( ) ) ; } 
List < Integer > pluck ( List < Integer > arr ) { List < Integer > result = new ArrayList < > ( ) ; for ( int i = 0 ; i < arr . size ( ) ; i ++ ) { if ( arr . get ( i ) % 2 == 0 ) { if ( result . isEmpty ( ) ) { result . add ( arr . get ( i ) ) ; result . add ( i ) ; } else if ( arr . get ( i ) < result . get ( 0 ) ) { result . set ( 0 , arr . get ( i ) ) ; result . set ( 1 , i ) ; } } } return result ; } 
List < Integer > strangeSortList ( List < Integer > lst ) { List < Integer > res = new ArrayList < > ( ) ; Collections . sort ( lst ) ; int l = 0 ; int r = lst . size ( ) - 1 ; while ( l < r ) { res . add ( lst . get ( l ) ) ; l += 1 ; res . add ( lst . get ( r ) ) ; r -= 1 ; } if ( l == r ) { res . add ( lst . get ( l ) ) ; } return res ; } 
double triangleArea ( double a , double b , double c ) { if ( a + b <= c || a + c <= b || b + c <= a ) { return - 1 ; } double s = ( a + b + c ) / 2 ; return Math . sqrt ( s * ( s - a ) * ( s - b ) * ( s - c ) ) ; } 
boolean willItFly ( List < Integer > q , int w ) { int sum = 0 ; for ( int i = 0 ; i < q . size ( ) ; i ++ ) { if ( ! q . get ( i ) . equals ( q . get ( q . size ( ) - i - 1 ) ) ) { return false ; } sum += q . get ( i ) ; } return sum <= w ; } 
boolean isCube ( int a ) { a = Math . abs ( a ) ; int i = ( int ) Math . round ( Math . pow ( a , 1.0 / 3 ) ) ; return ( int ) Math . pow ( i , 3 ) == a ; } 
int hexKey ( String num ) { String key = "2357BD" ; int total = 0 ; for ( char c : num . toCharArray ( ) ) { if ( key . indexOf ( c ) != - 1 ) { total += 1 ; } } return total ; } 
String decimalToBinary ( int dec ) { StringBuilder ans = new StringBuilder ( ) ; if ( dec != 0 ) { while ( dec > 0 ) { ans . insert ( 0 , dec % 2 ) ; dec /= 2 ; } } else { ans . append ( "0" ) ; } return "db" + ans . toString ( ) + "db" ; } 
boolean primeLength ( String s ) { int l = s . length ( ) ; if ( l < 2 ) { return false ; } for ( int i = 2 ; i < l ; i ++ ) { if ( l % i == 0 ) { return false ; } } return true ; } 
int startsOneEnds ( int n ) { if ( n < 1 ) { return 0 ; } if ( n == 1 ) { return 1 ; } return ( int ) ( 18 * Math . pow ( 10 , n - 2 ) ) ; } 
int add ( List < Integer > lst ) { int sum = 0 ; for ( int i = 1 ; i < lst . size ( ) ; i += 2 ) { if ( lst . get ( i ) % 2 == 0 ) { sum += lst . get ( i ) ; } } return sum ; } 
List < List < Integer > > getRow ( List < List < Integer > > lst , int x ) { List < List < Integer > > coords = new ArrayList < > ( ) ; for ( int i = 0 ; i < lst . size ( ) ; i ++ ) { for ( int j = lst . get ( i ) . size ( ) - 1 ; j >= 0 ; j -- ) { if ( lst . get ( i ) . get ( j ) == x ) { coords . add ( Arrays . asList ( i , j ) ) ; } } } return coords ; } 
int nextSmallest ( List < Integer > lst ) { Collections . sort ( lst ) ; for ( int i = 1 ; i < lst . size ( ) ; i ++ ) { if ( ! lst . get ( i ) . equals ( lst . get ( i - 1 ) ) ) { return lst . get ( i ) ; } } return - 1 ; } 
boolean anyInt ( double a , double b , double c ) { if ( Math . round ( a ) != a || Math . round ( b ) != b || Math . round ( c ) != c ) { return false ; } return a + b == c || a + c == b || b + c == a ; } 
List < Integer > countUpTo ( int n ) { List < Integer > primes = new ArrayList < > ( ) ; for ( int i = 2 ; i < n ; i ++ ) { boolean isPrime = true ; for ( int j = 2 ; j < i ; j ++ ) { if ( i % j == 0 ) { isPrime = false ; break ; } } if ( isPrime ) { primes . add ( i ) ; } } return primes ; } 
int closestInteger ( String value ) { double w = Double . parseDouble ( value ) ; return ( int ) Math . round ( w ) ; } 
List < Integer > makeAPile ( int n ) { List < Integer > result = new ArrayList < > ( ) ; for ( int i = 0 ; i < n ; i ++ ) { result . add ( n + 2 * i ) ; } return result ; } 
List < String > wordStrings ( String s ) { StringBuilder current = new StringBuilder ( ) ; List < String > words = new ArrayList < > ( ) ; for ( int i = 0 ; i <= s . length ( ) ; i ++ ) { if ( i == s . length ( ) || s . charAt ( i ) == ' ' || s . charAt ( i ) == ',' ) { if ( current . length ( ) > 0 ) { words . add ( current . toString ( ) ) ; current . setLength ( 0 ) ; } } else { current . append ( s . charAt ( i ) ) ; } } return words ; } 
String roundedAvg ( int n , int m ) { if ( n > m ) { return "-1" ; } int num = ( m + n ) / 2 ; StringBuilder ret = new StringBuilder ( ) ; while ( num > 0 ) { ret . insert ( 0 , num % 2 ) ; num /= 2 ; } return ret . toString ( ) ; } 
List < Integer > uniqueDigits ( List < Integer > x ) { List < Integer > digits = new ArrayList < > ( ) ; for ( int i : x ) { boolean isUnique = true ; for ( char c : String . valueOf ( i ) . toCharArray ( ) ) { if ( c % 2 == 0 ) { isUnique = false ; break ; } } if ( isUnique ) { digits . add ( i ) ; } } Collections . sort ( digits ) ; return digits ; } 
int countNums ( List < Integer > arr ) { int num = 0 ; for ( int n : arr ) { int neg = n < 0 ? - 1 : 1 ; n = Math . abs ( n ) ; List < Integer > digits = new ArrayList < > ( ) ; for ( char c : String . valueOf ( n ) . toCharArray ( ) ) { digits . add ( c - '0' ) ; } digits . set ( 0 , digits . get ( 0 ) * neg ) ; int sum = 0 ; for ( int d : digits ) { sum += d ; } if ( sum > 0 ) { num += 1 ; } } return num ; } 
boolean moveOneBall ( List < Integer > arr ) { if ( arr . isEmpty ( ) ) { return true ; } int num = 0 ; for ( int i = 1 ; i < arr . size ( ) ; i ++ ) { if ( arr . get ( i ) < arr . get ( i - 1 ) ) { num += 1 ; } } if ( arr . get ( arr . size ( ) - 1 ) > arr . get ( 0 ) ) { num += 1 ; } if ( num < 2 ) { return true ; } return false ; } 
String exchange ( List < Integer > lst1 , List < Integer > lst2 ) { int odd = 0 ; int even = 0 ; for ( int n : lst1 ) { if ( n % 2 == 1 ) { odd += 1 ; } } for ( int n : lst2 ) { if ( n % 2 == 0 ) { even += 1 ; } } if ( even >= odd ) { return "YES" ; } return "NO" ; } 
List < String > oddCount ( List < String > lst ) { List < String > results = new ArrayList < > ( ) ; String originalStr = "the number of odd elements in the string i of the input." ; for ( String s : lst ) { int sum = 0 ; for ( char d : s . toCharArray ( ) ) { if ( Character . isDigit ( d ) && d % 2 == 1 ) { sum += 1 ; } } StringBuilder result = new StringBuilder ( ) ; for ( char c : originalStr . toCharArray ( ) ) { if ( c == 'i' ) { result . append ( sum ) ; } else { result . append ( c ) ; } } results . add ( result . toString ( ) ) ; } return results ; } 
int minSubArraySum ( List < Integer > nums ) { int minSum = Integer . MAX_VALUE ; int sum = 0 ; for ( int num : nums ) { sum += num ; if ( minSum > sum ) { minSum = sum ; } if ( sum > 0 ) { sum = 0 ; } } return minSum ; } 
int maxFill ( List < List < Integer > > grid , int capacity ) { int res = 0 ; for ( var well : grid ) { int sum = 0 ; for ( int n : well ) { sum += n ; } if ( sum > 0 ) { res += ( sum - 1 ) / capacity + 1 ; } } return res ; } 
List < String > selectWords ( String s , int n ) { String vowels = "aeiouAEIOU" ; StringBuilder current = new StringBuilder ( ) ; List < String > result = new ArrayList < > ( ) ; int consonantNum = 0 ; for ( int i = 0 ; i <= s . length ( ) ; i ++ ) { if ( i == s . length ( ) || s . charAt ( i ) == ' ' ) { if ( consonantNum == n ) { result . add ( current . toString ( ) ) ; } current . setLength ( 0 ) ; consonantNum = 0 ; } else { current . append ( s . charAt ( i ) ) ; if ( vowels . indexOf ( s . charAt ( i ) ) == - 1 ) { consonantNum += 1 ; } } } return result ; } 
int solution ( List < Integer > lst ) { int sum = 0 ; for ( int i = 0 ; i < lst . size ( ) ; i += 2 ) { if ( ( lst . get ( i ) % 2 ) == 1 ) { sum += lst . get ( i ) ; } } return sum ; } 
int addElements ( List < Integer > arr , int k ) { int sum = 0 ; for ( int i = 0 ; i < k ; i ++ ) { if ( arr . get ( i ) >= - 99 && arr . get ( i ) <= 99 ) { sum += arr . get ( i ) ; } } return sum ; } 
List < Integer > getOddCollatz ( int n ) { List < Integer > oddCollatz = new ArrayList < > ( ) ; while ( n != 1 ) { if ( n % 2 == 1 ) { oddCollatz . add ( n ) ; n = n * 3 + 1 ; } else { n /= 2 ; } } oddCollatz . add ( 1 ) ; Collections . sort ( oddCollatz ) ; return oddCollatz ; } 
boolean isSorted ( List < Integer > lst ) { for ( int i = 1 ; i < lst . size ( ) ; i ++ ) { if ( lst . get ( i ) < lst . get ( i - 1 ) ) { return false ; } if ( i >= 2 && lst . get ( i ) == lst . get ( i - 1 ) && lst . get ( i ) == lst . get ( i - 2 ) ) { return false ; } } return true ; } 
String intersection ( List < Integer > interval1 , List < Integer > interval2 ) { int inter1 = Math . max ( interval1 . get ( 0 ) , interval2 . get ( 0 ) ) ; int inter2 = Math . min ( interval1 . get ( 1 ) , interval2 . get ( 1 ) ) ; int l = inter2 - inter1 ; if ( l < 2 ) { return "NO" ; } for ( int i = 2 ; i < l ; i ++ ) { if ( l % i == 0 ) { return "NO" ; } } return "YES" ; } 
int prodSigns ( List < Integer > arr ) { if ( arr . isEmpty ( ) ) { return - 32768 ; } int sum = 0 ; int prods = 1 ; for ( int i : arr ) { sum += Math . abs ( i ) ; if ( i == 0 ) { prods = 0 ; } if ( i < 0 ) { prods = - prods ; } } return sum * prods ; } 
List < Integer > minPath ( List < List < Integer > > grid , int k ) { int n = grid . size ( ) ; int minNum = 0 ; for ( int i = 0 ; i < n ; i ++ ) { for ( int j = 0 ; j < n ; j ++ ) { if ( grid . get ( i ) . get ( j ) == 1 ) { List < Integer > tmp = new ArrayList < > ( ) ; if ( i != 0 ) { tmp . add ( grid . get ( i - 1 ) . get ( j ) ) ; } if ( j != 0 ) { tmp . add ( grid . get ( i ) . get ( j - 1 ) ) ; } if ( i != n - 1 ) { tmp . add ( grid . get ( i + 1 ) . get ( j ) ) ; } if ( j != n - 1 ) { tmp . add ( grid . get ( i ) . get ( j + 1 ) ) ; } minNum = Collections . min ( tmp ) ; } } } List < Integer > ans = new ArrayList < > ( ) ; for ( int i = 0 ; i < k ; i ++ ) { if ( i % 2 == 0 ) { ans . add ( 1 ) ; } else { ans . add ( minNum ) ; } } return ans ; } 
int digits ( int n ) { int prod = 0 ; for ( char digit : String . valueOf ( n ) . toCharArray ( ) ) { if ( digit % 2 == 1 ) { if ( prod == 0 ) { prod = 1 ; } prod *= digit - '0' ; } } return prod ; } 
boolean isNested ( String s ) { int count = 0 ; int maxCount = 0 ; for ( char ch : s . toCharArray ( ) ) { if ( ch == '[' ) { count += 1 ; } if ( ch == ']' ) { count -= 1 ; } if ( count < 0 ) { count = 0 ; } if ( count > maxCount ) { maxCount = count ; } if ( count <= maxCount - 2 ) { return true ; } } return false ; } 
int sumSquares ( List < Double > lst ) { int sum = 0 ; for ( double i : lst ) { sum += Math . ceil ( i ) * Math . ceil ( i ) ; } return sum ; } 
int canArrange ( List < Integer > arr ) { int index = - 1 ; for ( int i = 0 ; i < arr . size ( ) ; i ++ ) { if ( arr . get ( i ) <= i ) { index = i ; } } return index ; } 
List < Integer > largestSmallestIntegers ( List < Integer > lst ) { int maxNeg = 0 , minPos = 0 ; for ( int n : lst ) { if ( n < 0 && ( maxNeg == 0 || n > maxNeg ) ) { maxNeg = n ; } if ( n > 0 && ( minPos == 0 || n < minPos ) ) { minPos = n ; } } return Arrays . asList ( maxNeg , minPos ) ; } 
String fixSpaces ( String text ) { StringBuilder res = new StringBuilder ( ) ; int spaceLen = 0 ; for ( int i = 0 ; i <= text . length ( ) ; i ++ ) { if ( i == text . length ( ) || text . charAt ( i ) != ' ' ) { if ( spaceLen == 1 ) { res . append ( '_' ) ; } if ( spaceLen == 2 ) { res . append ( "__" ) ; } if ( spaceLen > 2 ) { res . append ( '-' ) ; } spaceLen = 0 ; if ( i != text . length ( ) ) { res . append ( text . charAt ( i ) ) ; } } else { spaceLen += 1 ; } } return res . toString ( ) ; } 
String filenameCheck ( String fileName ) { int digitNum = 0 , dotNum = 0 ; if ( fileName . length ( ) < 5 || ! Character . isLetter ( fileName . charAt ( 0 ) ) ) { return "No" ; } String suffix = fileName . substring ( fileName . length ( ) - 4 ) ; if ( ! suffix . equals ( ".txt" ) && ! suffix . equals ( ".exe" ) && ! suffix . equals ( ".dll" ) ) { return "No" ; } for ( char c : fileName . toCharArray ( ) ) { if ( Character . isDigit ( c ) ) { digitNum += 1 ; } if ( c == '.' ) { dotNum += 1 ; } } if ( digitNum > 3 || dotNum != 1 ) { return "No" ; } return "Yes" ; } 
int sumSquares ( List < Integer > lst ) { int sum = 0 ; for ( int i = 0 ; i < lst . size ( ) ; i ++ ) { if ( i % 3 == 0 ) { sum += lst . get ( i ) * lst . get ( i ) ; } else if ( i % 4 == 0 ) { sum += lst . get ( i ) * lst . get ( i ) * lst . get ( i ) ; } else { sum += lst . get ( i ) ; } } return sum ; } 
String wordsInSentence ( String sentence ) { StringBuilder result = new StringBuilder ( ) ; StringBuilder current = new StringBuilder ( ) ; for ( int i = 0 ; i <= sentence . length ( ) ; i ++ ) { if ( i == sentence . length ( ) || sentence . charAt ( i ) == ' ' ) { boolean isPrime = true ; int l = current . length ( ) ; if ( l < 2 ) { isPrime = false ; } for ( int j = 2 ; j < l ; j ++ ) { if ( l % j == 0 ) { isPrime = false ; break ; } } if ( isPrime ) { result . append ( current . toString ( ) ) . append ( ' ' ) ; } current . setLength ( 0 ) ; } else { current . append ( sentence . charAt ( i ) ) ; } } if ( result . length ( ) > 0 ) { result . deleteCharAt ( result . length ( ) - 1 ) ; } return result . toString ( ) ; } 
boolean simplify ( String x , String n ) { int a = 0 , b = 0 , c = 0 , d = 0 ; for ( int i = 0 ; i < x . length ( ) ; i ++ ) { if ( x . charAt ( i ) == '/' ) { a = Integer . parseInt ( x . substring ( 0 , i ) ) ; b = Integer . parseInt ( x . substring ( i + 1 ) ) ; } } for ( int i = 0 ; i < n . length ( ) ; i ++ ) { if ( n . charAt ( i ) == '/' ) { c = Integer . parseInt ( n . substring ( 0 , i ) ) ; d = Integer . parseInt ( n . substring ( i + 1 ) ) ; } } return ( a * c ) % ( b * d ) == 0 ; } 
int specialFilter ( List < Integer > nums ) { int count = 0 ; for ( int num : nums ) { if ( num > 10 ) { String w = String . valueOf ( num ) ; if ( w . charAt ( 0 ) % 2 == 1 && w . charAt ( w . length ( ) - 1 ) % 2 == 1 ) { count += 1 ; } } } return count ; } 
int getMaxTriples ( int n ) { List < Integer > arr = new ArrayList < > ( ) ; for ( int i = 1 ; i <= n ; i ++ ) { arr . add ( i * i - i + 1 ) ; } int count = 0 ; for ( int i = 0 ; i < n ; i ++ ) { for ( int j = i + 1 ; j < n ; j ++ ) { for ( int k = j + 1 ; k < n ; k ++ ) { if ( ( arr . get ( i ) + arr . get ( j ) + arr . get ( k ) ) % 3 == 0 ) { count += 1 ; } } } } return count ; } 
int doubleTheDifference ( List < Double > lst ) { int sum = 0 ; for ( double d : lst ) { int num = ( int ) Math . round ( d ) ; if ( d == num ) { if ( num > 0 && num % 2 == 1 ) { sum += num * num ; } } } return sum ; } 
List < Integer > compare ( List < Integer > game , List < Integer > guess ) { List < Integer > result = new ArrayList < > ( ) ; for ( int i = 0 ; i < game . size ( ) ; i ++ ) { result . add ( Math . abs ( game . get ( i ) - guess . get ( i ) ) ) ; } return result ; } 
String strongestExtension ( String className , List < String > extensions ) { String strongest = "" ; int max = Integer . MIN_VALUE ; for ( var extension : extensions ) { int strength = 0 ; for ( char chr : extension . toCharArray ( ) ) { if ( Character . isUpperCase ( chr ) ) { strength += 1 ; } if ( Character . isLowerCase ( chr ) ) { strength -= 1 ; } } if ( strength > max ) { max = strength ; strongest = extension ; } } return className + '.' + strongest ; } 
String intToMiniRoman ( int number ) { List < Integer > num = Arrays . asList ( 1000 , 900 , 500 , 400 , 100 , 90 , 50 , 40 , 10 , 9 , 5 , 4 , 1 ) ; List < String > sym = Arrays . asList ( "m" , "cm" , "d" , "cd" , "c" , "xc" , "l" , "xl" , "x" , "ix" , "v" , "iv" , "i" ) ; int pos = 0 ; StringBuilder res = new StringBuilder ( ) ; while ( number > 0 ) { while ( number >= num . get ( pos ) ) { res . append ( sym . get ( pos ) ) ; number -= num . get ( pos ) ; } if ( number > 0 ) { pos += 1 ; } } return res . toString ( ) ; } 
List < Integer > eat ( int number , int need , int remaining ) { return need > remaining ? Arrays . asList ( number + remaining , 0 ) : Arrays . asList ( number + need , remaining - need ) ; } 
int doAlgebra ( List < String > ops , List < Integer > operands ) { List < Integer > nums = new ArrayList < > ( operands ) ; List < String > currentOps = new ArrayList < > ( ops ) ; int i = currentOps . size ( ) - 1 ; while ( i >= 0 ) { if ( currentOps . get ( i ) . equals ( "**" ) ) { nums . set ( i , ( int ) Math . pow ( nums . get ( i ) , nums . get ( i + 1 ) ) ) ; nums . remove ( i + 1 ) ; currentOps . remove ( i ) ; } i -- ; } i = 0 ; while ( i < currentOps . size ( ) ) { if ( currentOps . get ( i ) . equals ( "*" ) ) { nums . set ( i , nums . get ( i ) * nums . get ( i + 1 ) ) ; nums . remove ( i + 1 ) ; currentOps . remove ( i ) ; } else if ( currentOps . get ( i ) . equals ( "//" ) ) { nums . set ( i , nums . get ( i ) / nums . get ( i + 1 ) ) ; nums . remove ( i + 1 ) ; currentOps . remove ( i ) ; } else { i ++ ; } } i = 0 ; while ( i < currentOps . size ( ) ) { if ( currentOps . get ( i ) . equals ( "+" ) ) { nums . set ( i , nums . get ( i ) + nums . get ( i + 1 ) ) ; nums . remove ( i + 1 ) ; currentOps . remove ( i ) ; } else if ( currentOps . get ( i ) . equals ( "-" ) ) { nums . set ( i , nums . get ( i ) - nums . get ( i + 1 ) ) ; nums . remove ( i + 1 ) ; currentOps . remove ( i ) ; } else { i ++ ; } } return nums . get ( 0 ) ; } 
List < Integer > generateIntegers ( int a , int b ) { int lower = Math . max ( 2 , Math . min ( a , b ) ) ; int upper = Math . min ( 8 , Math . max ( a , b ) ) ; List < Integer > result = new ArrayList < > ( ) ; for ( int i = lower ; i <= upper ; i += 2 ) { result . add ( i ) ; } return result ; }
boolean isStepNum ( int n ) { int prevDigit = - 1 ; while ( n > 0 ) { int curDigit = n % 10 ; if ( prevDigit != - 1 ) { if ( Math . abs ( curDigit - prevDigit ) != 1 ) { return false ; } } n /= 10 ; prevDigit = curDigit ; } return true ; }
int numOfWays ( int n , int k ) { int p = 1 ; if ( k % 2 != 0 ) { p = - 1 ; } return ( int ) ( Math . pow ( n - 1 , k ) + p * ( n - 1 ) ) / n ; } 
List < Integer > findDivisors ( int n ) { List < Integer > v = new ArrayList < > ( ) ; for ( int i = 1 ; i <= Math . sqrt ( n ) ; i ++ ) { if ( n % i == 0 ) { if ( n / i == i ) { v . add ( i ) ; } else { v . add ( i ) ; v . add ( n / i ) ; } } } return v ; } 
int eggDrop ( int n , int k ) { if ( k == 1 || k == 0 ) { return k ; } if ( n == 1 ) { return k ; } int min = Integer . MAX_VALUE ; int x , res ; for ( x = 1 ; x <= k ; x ++ ) { res = Math . max ( eggDrop ( n - 1 , x - 1 ) , eggDrop ( n , k - x ) ) ; if ( res < min ) { min = res ; } } return min + 1 ; } 
boolean isPowerOfTwo ( int n ) { if ( n == 0 ) { return false ; } return Math . ceil ( Math . log ( n ) / Math . log ( 2 ) ) == Math . floor ( Math . log ( n ) / Math . log ( 2 ) ) ; } 
String shortestPalindrome ( String s ) { int n = s . length ( ) ; List < String > v = new ArrayList < String > ( ) ; for ( int i = 0 ; i < n ; i ++ ) { int l = i ; int r = i ; String ans1 = "" ; String ans2 = "" ; while ( l >= 0 && r < n && s . charAt ( l ) == s . charAt ( r ) ) { ans1 += s . charAt ( l ) ; l -- ; r ++ ; } l = i - 1 ; r = i ; while ( l >= 0 && r < n && s . charAt ( l ) == s . charAt ( r ) ) { ans2 += s . charAt ( l ) ; l -- ; r ++ ; } v . add ( ans1 ) ; v . add ( ans2 ) ; } String ans = v . get ( 0 ) ; for ( int i = 0 ; i < v . size ( ) ; i ++ ) { if ( v . get ( i ) != "" ) { if ( ans . charAt ( 0 ) >= v . get ( i ) . charAt ( 0 ) ) { ans = v . get ( i ) ; } } } return ans ; } 
int minimumAdjacentDifference ( List < Integer > a , int n , int k ) { int minDiff = Integer . MAX_VALUE ; for ( int i = 0 ; i <= k ; i ++ ) { int maxDiff = Integer . MIN_VALUE ; for ( int j = 0 ; j < n - k - 1 ; j ++ ) { for ( int p = i ; p <= i + j ; p ++ ) { maxDiff = Math . max ( maxDiff , a . get ( p + 1 ) - a . get ( p ) ) ; } } minDiff = Math . min ( minDiff , maxDiff ) ; } return minDiff ; } 
int cal ( List < Integer > arr , int mid ) { int chocolate = 0 ; for ( var i : arr ) { if ( i >= mid ) { chocolate += i - mid ; } } return chocolate ; }
boolean check ( int v , List < Integer > a , int m ) { int tec = 0 , ans = 0 ; List < Integer > b = new ArrayList < > ( Collections . nCopies ( a . size ( ) + 3 , 0 ) ) ; for ( int i = 0 ; i < a . size ( ) ; i ++ ) { tec -= b . get ( i ) ; if ( a . get ( i ) + tec < v ) { int mov = v - a . get ( i ) - tec ; ans = ans + mov ; tec += mov ; b . set ( i + 2 , mov ) ; } } return ans <= m ; } 
int largestNum ( List < Integer > arr ) { int res = 0 ; Collections . sort ( arr ) ; int l = 0 , r = arr . size ( ) - 1 ; while ( l < r ) { int sum = arr . get ( l ) + arr . get ( r ) ; if ( sum == 0 ) { res = Math . max ( res , Math . max ( arr . get ( l ) , arr . get ( r ) ) ) ; return res ; } else if ( sum < 0 ) { l ++ ; } else { r -- ; } } return res ; } 
int binarySearch ( List < Integer > p , int n ) { int i = 0 ; int j = p . size ( ) - 1 ; int index = - 1 ; while ( i <= j ) { int mid = i + ( j - i ) / 2 ; if ( p . get ( mid ) >= n ) { index = mid ; j = mid - 1 ; } else { i = mid + 1 ; } } return index ; } 
int findMinLength ( List < Integer > arr ) { int index = arr . size ( ) - 1 ; while ( index > 0 && arr . get ( index ) >= arr . get ( index - 1 ) ) { index -- ; } return index ; } 
int minDigits ( int n , int k ) { int digitsNum = ( int ) Math . floor ( Math . log ( n ) + 1 ) ; int tempSum = 0 ; int temp = digitsNum ; int result = 0 ; int x , v ; int sum = 0 ; int num2 = n ; while ( num2 != 0 ) { sum += num2 % 10 ; num2 /= 10 ; } if ( sum <= k ) { x = 0 ; } else { while ( temp > 0 ) { v = n / ( int ) Math . pow ( 10 , temp - 1 ) ; tempSum += v % 10 ; if ( tempSum >= k ) { v /= 10 ; v ++ ; result = v * ( int ) Math . pow ( 10 , temp ) ; break ; } temp -- ; } x = result - n ; return x ; } return - 1 ; } 
int checkForPerfectSquare ( List < Integer > arr , int i , int j ) { int mid , sum = 0 ; for ( int m = i ; m <= j ; m ++ ) { sum += arr . get ( m ) ; } int low = 0 , high = sum / 2 ; while ( low <= high ) { mid = low + ( high - low ) / 2 ; if ( mid * mid == sum ) { return mid ; } else if ( mid * mid > sum ) { high = mid - 1 ; } else { low = mid + 1 ; } } return - 1 ; } 
int minFlips ( List < List < Integer > > mat , String s ) { int n = mat . size ( ) ; int m = mat . get ( 0 ) . size ( ) ; int count = 0 ; for ( int i = 0 ; i < n ; i ++ ) { for ( int j = 0 ; j < m ; j ++ ) { if ( mat . get ( i ) . get ( j ) != s . charAt ( i + j ) - '0' ) { count ++ ; } } } return count ; } 
List < List < Integer > > constructTree ( int n , List < List < Integer > > edges ) { List < List < Integer > > adjl = new ArrayList < > ( ) ; for ( int i = 0 ; i < n ; i ++ ) { adjl . add ( new ArrayList < > ( ) ) ; } for ( var e : edges ) { int u = e . get ( 0 ) ; int v = e . get ( 1 ) ; adjl . get ( u ) . add ( v ) ; adjl . get ( v ) . add ( u ) ; } return adjl ; } 
int findSumOfValues ( int v , List < Integer > parent , List < Integer > valuesChildren ) { int curNode = v ; int sum = 0 ; while ( curNode != - 1 ) { sum += valuesChildren . get ( curNode ) ; curNode = parent . get ( curNode ) ; } return sum ; } 
int getDistinct ( int d , int count ) { int num = 0 ; count = ( int ) Math . pow ( 10 , count - 1 ) ; while ( count > 0 ) { num += count * d ; count /= 10 ; } return num ; } 
boolean isIncreasing ( List < Integer > arr ) { for ( int i = 0 ; i < arr . size ( ) - 1 ; i ++ ) { if ( arr . get ( i ) > arr . get ( i + 1 ) ) { return false ; } } return true ; } 
int minAdjSwaps ( List < List < Integer > > mat ) { int n = mat . size ( ) ; List < Integer > cntZero = new ArrayList < > ( Collections . nCopies ( n , 0 ) ) ; for ( int i = 0 ; i < n ; i ++ ) { for ( int j = n - 1 ; j >= 0 && mat . get ( i ) . get ( j ) == 0 ; j -- ) { cntZero . set ( i , cntZero . get ( i ) + 1 ) ; } } int cntSwaps = 0 ; for ( int i = 0 ; i < n ; i ++ ) { if ( cntZero . get ( i ) < ( n - i - 1 ) ) { int first = i ; while ( first < n && cntZero . get ( first ) < ( n - i - 1 ) ) { first ++ ; } if ( first == n ) { return - 1 ; } while ( first > i ) { Collections . swap ( cntZero , first , first - 1 ) ; first -- ; cntSwaps ++ ; } } } return cntSwaps ; } 
int solve ( List < Integer > values , List < Integer > salary , int mod ) { int ret = 1 ; int amt = 0 ; Collections . sort ( values ) ; Collections . sort ( salary ) ; while ( salary . size ( ) > 0 ) { while ( values . size ( ) > 0 && values . get ( values . size ( ) - 1 ) >= salary . get ( salary . size ( ) - 1 ) ) { amt ++ ; values . remove ( values . size ( ) - 1 ) ; } if ( amt == 0 ) { return 0 ; } ret *= amt -- ; ret %= mod ; salary . remove ( salary . size ( ) - 1 ) ; } return ret ; } 
List < Integer > organizeInOrder ( List < Integer > vec , List < Character > op , int n ) { List < Integer > result = new ArrayList < > ( Collections . nCopies ( n , 0 ) ) ; Collections . sort ( vec ) ; int i = 0 , j = n - 1 , k = 0 ; while ( i <= j && k <= n - 2 ) { if ( op . get ( k ) == '<' ) { result . set ( k , vec . get ( i ++ ) ) ; } else { result . set ( k , vec . get ( j -- ) ) ; } k ++ ; } result . set ( n - 1 , vec . get ( i ) ) ; return result ; } 
int countPoints ( int n , int m , List < Integer > a , List < Integer > b , int x , int y ) { Collections . sort ( a ) ; Collections . sort ( b ) ; int j = 0 ; int count = 0 ; for ( int i = 0 ; i < n ; i ++ ) { while ( j < m ) { if ( a . get ( i ) + y < b . get ( j ) ) { break ; } if ( b . get ( j ) >= a . get ( i ) - x && b . get ( j ) <= a . get ( i ) + y ) { count ++ ; j ++ ; break ; } else { j ++ ; } } } return count ; } 
boolean areSame ( List < Integer > a , List < Integer > b ) { Collections . sort ( a ) ; Collections . sort ( b ) ; return a . equals ( b ) ; } 
int countNumberOfStrings ( String s ) { int n = s . length ( ) - 1 ; int count = ( int ) Math . pow ( 2 , n ) ; return count ; } 
List < Integer > primePower ( int x ) { List < Integer > primePow = new ArrayList < > ( ) ; for ( int i = 2 ; i * i <= x ; i ++ ) { if ( x % i == 0 ) { int p = 1 ; while ( x % i == 0 ) { x /= i ; p *= i ; } primePow . add ( p ) ; } } if ( x > 1 ) { primePow . add ( x ) ; } return primePow ; } 
boolean isPerfect ( int n0 ) { double n = Math . sqrt ( n0 ) ; if ( Math . floor ( n ) != Math . ceil ( n ) ) { return false ; } return true ; } 
int findSum ( int l , int r ) { List < Integer > arr = new ArrayList < > ( ) ; int i = 0 ; int x = 2 ; while ( i <= r ) { arr . add ( i + x ) ; if ( i + 1 <= r ) { arr . add ( i + 1 + x ) ; } x *= - 1 ; i += 2 ; } int sum = 0 ; for ( i = l ; i <= r ; ++ i ) { sum += arr . get ( i ) ; } return sum ; } 
int results ( int n , int k ) { return ( int ) Math . round ( Math . pow ( n , 1.0 / Math . pow ( 2.0 , k ) ) ) ; } 
List < Integer > factors ( int n ) { List < Integer > v = new ArrayList < > ( ) ; v . add ( 1 ) ; for ( int i = 2 ; i <= Math . sqrt ( n ) ; i ++ ) { if ( n % i == 0 ) { v . add ( i ) ; if ( n / i != i ) { v . add ( n / i ) ; } } } return v ; } 
int smallestNum ( int n ) { double x = Math . pow ( 10 , ( n - 1 ) / 2.0 ) ; return ( int ) Math . ceil ( x ) ; } 
int smallest ( String s ) { List < Integer > a = new ArrayList < > ( Collections . nCopies ( s . length ( ) , 0 ) ) ; for ( int i = 0 ; i < s . length ( ) ; i ++ ) { a . set ( i , s . charAt ( i ) - '0' ) ; } List < Integer > b = new ArrayList < > ( ) ; for ( int i = 0 ; i < a . size ( ) ; i ++ ) { if ( a . get ( i ) % 2 != 0 ) { b . add ( a . get ( i ) ) ; } } Collections . sort ( b ) ; if ( b . size ( ) > 1 ) { return b . get ( 0 ) * 10 + b . get ( 1 ) ; } return - 1 ; } 
List < Double > Diagonals ( double a , double b , double c , double d ) { List < Double > ans = new ArrayList < > ( ) ; ans . add ( Math . sqrt ( ( a * c + b * d ) * ( a * d + b * c ) / ( a * b + c * d ) ) ) ; ans . add ( Math . sqrt ( ( a * c + b * d ) * ( a * b + c * d ) / ( a * d + b * c ) ) ) ; return ans ; } 
int findNumberOfDigits ( int n , int bas ) { int dig = ( int ) Math . floor ( Math . log ( n ) / Math . log ( bas ) ) + 1 ; return dig ; } 
double nGon ( int n ) { double proAngleVar ; if ( n % 4 == 0 ) { proAngleVar = Math . PI * ( 180.0 / n ) / 180 ; } else { proAngleVar = Math . PI * ( 180.0 / ( 2 * n ) ) / 180 ; } double negX = 1.0e+99 , posX = - 1.0e+99 , negY = 1.0e+99 , posY = - 1.0e+99 ; for ( int j = 0 ; j < n ; ++ j ) { double px = Math . cos ( 2 * Math . PI * j / n + proAngleVar ) ; double py = Math . sin ( 2 * Math . PI * j / n + proAngleVar ) ; negX = Math . min ( negX , px ) ; posX = Math . max ( posX , px ) ; negY = Math . min ( negY , py ) ; posY = Math . max ( posY , py ) ; } double opt2 = Math . max ( posX - negX , posY - negY ) ; return opt2 / Math . sin ( Math . PI / n ) / 2 ; } 
int findMaxK ( int n ) { int p = ( int ) ( Math . log ( n ) / Math . log ( 2 ) ) ; return ( int ) Math . pow ( 2 , p ) ; } 
int nthFibo ( int n ) { double a = ( Math . pow ( 5 , 0.5 ) + 1 ) / 2 ; double b = ( - 1 * Math . pow ( 5 , 0.5 ) + 1 ) / 2 ; double r = Math . pow ( 5 , 0.5 ) ; double ans = ( Math . pow ( a , n ) - Math . pow ( b , n ) ) / r ; return ( int ) ans ; } 
double findProb ( int l , int r ) { double countOfPs = Math . floor ( Math . sqrt ( r ) ) - Math . ceil ( Math . sqrt ( l ) ) + 1 ; double total = r - l + 1 ; double prob = countOfPs / total ; return prob ; } 
int previousFibonacci ( int n ) { double a = n / ( ( 1 + Math . sqrt ( 5 ) ) / 2.0 ) ; return ( int ) Math . round ( a ) ; } 
List < Integer > distPrime ( List < Integer > arr , List < Integer > allPrimes ) { List < Integer > list1 = new ArrayList < > ( ) ; for ( int i : allPrimes ) { for ( int j : arr ) { if ( j % i == 0 ) { list1 . add ( i ) ; break ; } } } return list1 ; } 
List < Integer > getArray ( int n ) { List < Integer > ans = new ArrayList < > ( ) ; int p2 = 1 ; while ( n > 0 ) { if ( n % 2 == 1 ) { ans . add ( p2 ) ; } n >>= 1 ; p2 *= 2 ; } return ans ; } 
int maximumLength ( List < Integer > a ) { List < Integer > counts = new ArrayList < > ( Collections . nCopies ( 11 , 0 ) ) ; int ans = 0 ; for ( int index = 0 ; index < a . size ( ) ; index ++ ) { counts . set ( a . get ( index ) , counts . get ( a . get ( index ) ) + 1 ) ; List < Integer > k = new ArrayList < > ( ) ; for ( var i : counts ) { if ( i != 0 ) { k . add ( i ) ; } } Collections . sort ( k ) ; if ( k . size ( ) == 1 || ( k . get ( 0 ) == k . get ( k . size ( ) - 2 ) && k . get ( k . size ( ) - 1 ) - k . get ( k . size ( ) - 2 ) == 1 ) || ( k . get ( 0 ) == 1 && k . get ( 1 ) == k . get ( k . size ( ) - 1 ) ) ) { ans = index ; } } return ans + 1 ; } 
int maxEdges ( double n ) { double edges = Math . floor ( n * n / 4 ) ; return ( int ) edges ; } 
int findK ( int n , int k ) { List < Integer > a = new ArrayList < > ( ) ; for ( int i = 1 ; i < n ; i ++ ) { if ( i % 2 == 1 ) { a . add ( i ) ; } } for ( int i = 1 ; i < n ; i ++ ) { if ( i % 2 == 0 ) { a . add ( i ) ; } } return a . get ( k - 1 ) ; } 
boolean isKeith ( int x , int temp ) { List < Integer > terms = new ArrayList < > ( ) ; int n = 0 ; while ( temp > 0 ) { terms . add ( temp % 10 ) ; temp = temp / 10 ; n ++ ; } Collections . reverse ( terms ) ; int nextTerm = 0 , i = n ; while ( nextTerm < x ) { nextTerm = 0 ; for ( int j = 1 ; j <= n ; j ++ ) { nextTerm += terms . get ( i - j ) ; } terms . add ( nextTerm ) ; i ++ ; } return nextTerm == x ; } 
boolean factors ( int n , int k ) { List < Integer > v = new ArrayList < > ( ) ; while ( n % 2 == 0 ) { v . add ( 2 ) ; n /= 2 ; } if ( v . size ( ) >= k ) { return true ; } for ( int i = 3 ; i * i <= n ; i += 2 ) { while ( n % i == 0 ) { n = n / i ; v . add ( i ) ; } if ( v . size ( ) >= k ) { return true ; } } if ( n > 2 ) { v . add ( n ) ; } if ( v . size ( ) >= k ) { return true ; } return false ; }
